<a href="https://colab.research.google.com/github/leandro-adal/Eleicoes2020-AL/blob/main/Analise_nas_tabelas_Elei%C3%A7%C3%B5es_2020.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Eleições Municipais 2020**

Fonte dos dados: [Dados abertos - TSE](https://dadosabertos.tse.jus.br/)

As tabelas podem ser baixadas nos links abaixo:
1.   https://dadosabertos.tse.jus.br/dataset/comparecimento-e-abstencao-2020 - Comparecimento e Abstenção na votação de 2020
2.   https://dadosabertos.tse.jus.br/dataset/candidatos-2020-subtemas - Informações sobre os candidatos que disputaram a eleição em 2020
2. https://dadosabertos.tse.jus.br/dataset/resultados-2020 - Dados sobre o resultado da votação

## Criando ambiente e importando bibliotecas

In [ ]:
from google.colab import drive
drive.mount('/content/drive/')

Mounted at /content/drive/


In [ ]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

# Verificando como os dados estão sendo representados nas tabelas

## Tabelas

### Tabela 1 - Detalhes Candidatos

#### Descrição dos principais atributos

**Pricipais atributos do dataset**: 

*   NR_TURNO - Número do Turno
*   CD_ELEICAO - Código único da eleição
* NM_UE - Município que candidato concorre
*   DS_CARGO - Cargo ao qual o candidato concorre na eleição
*   NM_CANDIDATO - Nome completo do candidato
*   NM_SOCIAL_CANDIDATO - Nome social do candidato
*   DS_DETALHE_SITUACAO_CAND - Detalhe da situação do registro de candidatura do candidato que especifica o motivo pelo qual a candidatura foi julgada como 'Apta' ou 'Inapta'. 
*   SG_PARTIDO - Sigla do partido de origem do candidato
*   DT_NASCIMENTO - Data de nascimento do candidato
*   NR_IDADE_DATA_POSSE - idade do candidato na data da posse
* DS_GENERO - Gênero do candidato 
* DS_GRAU_INSTRUCAO - 
* DS_ESTADO_CIVIL - Estado civil do candidato 
* DS_COR_RACA - Cor/raça do candidato
* DS_OCUPACAO - Ocupação do candidato
* VR_DESPESA_MAX_CAMPANHA - Valor máximo, em reais, de despesas de campanha 
declarada pelo partido para aquele candidato
* DS_SIT_TOT_TURNO - Situação de totalização do candidato, naquele turno da 
eleição, após a totalização dos votos. 
 
* ST_REELEICAO - indica se o candidato está concorrendo ou não à reeleição



Destaques: VR_DESPESA_MAX_CAMPANHA, DS_GENERO, DS_CARGO, NM_CANDIDATO, NR_IDADE_DATA_POSSE, DS_COR_RACA, DS_OCUPACAO


**Quantidade de linhas** = 7583

**Quantidade de Municipios** =  102

**Problemas encontrados**:  

#### Lendo a tabela

In [ ]:
#Tabela com dados sobre os candidatos
colunasT1 = ['NR_TURNO', 'CD_ELEICAO','NM_UE', 'DS_CARGO','NM_URNA_CANDIDATO', 'DS_SIT_TOT_TURNO', 'DS_GENERO', 'VR_DESPESA_MAX_CAMPANHA', 'NM_CANDIDATO',
             'SQ_CANDIDATO', 'DS_SITUACAO_CANDIDATO_URNA','DS_SITUACAO_CANDIDATURA','DS_DETALHE_SITUACAO_CAND','ST_CANDIDATO_INSERIDO_URNA', 'SG_PARTIDO',
             'DT_NASCIMENTO','NR_IDADE_DATA_POSSE', 'DS_GRAU_INSTRUCAO', 'DS_ESTADO_CIVIL', 'DS_COR_RACA', 'CD_OCUPACAO', 'DS_OCUPACAO', 'ST_REELEICAO',
             'NR_CANDIDATO']
dados_candidatos = pd.read_csv('/content/drive/My Drive/Visualização Computacional/consulta_cand_2020_AL.csv', sep=";", encoding='latin-1', usecols=colunasT1)

In [ ]:
# Filtrando com base no código do 1º turno da eleição ordinaria
dados_candidatos = dados_candidatos.loc[(dados_candidatos['CD_ELEICAO'] == 426) ]

adicionar cor a municipio e partido

juntas as tabelas

add espectro

#### Visualizando a Tabela

In [ ]:
dados_candidatos.head(10)

NR_TURNO  CD_ELEICAO                  NM_UE  DS_CARGO  SQ_CANDIDATO  \
0         1         426                 VIÇOSA  VEREADOR   20000673350   
1         1         426  SÃO MIGUEL DOS CAMPOS  VEREADOR   20000922834   
2         1         426              ARAPIRACA  VEREADOR   20001257694   
3         1         426              PIAÇABUÇU  PREFEITO   20000797456   
4         1         426          SÃO SEBASTIÃO  VEREADOR   20000698660   
5         1         426          SÃO SEBASTIÃO  VEREADOR   20000698699   
6         1         426  PORTO REAL DO COLÉGIO  VEREADOR   20001120697   
7         1         426             BRANQUINHA  VEREADOR   20000973119   
8         1         426           CAMPO ALEGRE  VEREADOR   20000759145   
9         1         426               SÃO BRÁS  VEREADOR   20000744324   

   NR_CANDIDATO                       NM_CANDIDATO         NM_URNA_CANDIDATO  \
0         14555        ADEILTON ALEXANDRE FERREIRA            PAPAI FERREIRA   
1         25630             PETRÔNIO VERÇOSA LEMOS          PETRÔNIO VERÇOSA   
2         43456          MARIA JOSÉ LEITE DA SILVA  MARIA JOSÉ DA MANGABEIRA   
3            12  KAYRO CRISTÓVÃO CASTRO DOS SANTOS              KAYRO CASTRO   
4         11456     FHYSLAUREN FIRMINO ALBUQUERQUE    FHYSLAUREN ALBUQUERQUE   
5         77555        HENRIQUE GARCEZ DE OLIVEIRA           HENRIQUE GARCEZ   
6         10900  CRISLANE DE CASTRO DONATO FONSECA            CRIS DE TETEIA   
7         43000              ROBSON LOPES DE SOUZA            ROBINHO DO BAR   
8         14456        EDINALDO DOS SANTOS CANDIDO            IRMAO EDINALDO   
9         14444   WILLIAM DOUGLAS BEZERRA DA ROCHA          DOUGLAS DO GIRAU   

  DS_SITUACAO_CANDIDATURA DS_DETALHE_SITUACAO_CAND  ...  \
0                    APTO                 DEFERIDO  ...   
1                    APTO                 DEFERIDO  ...   
2                    APTO                 DEFERIDO  ...   
3                    APTO                 DEFERIDO  ...   
4                    APTO                 DEFERIDO  ...   
5                    APTO                 DEFERIDO  ...   
6                    APTO                 DEFERIDO  ...   
7                    APTO                 DEFERIDO  ...   
8                    APTO                 DEFERIDO  ...   
9                    APTO                 DEFERIDO  ...   

               DS_GRAU_INSTRUCAO DS_ESTADO_CIVIL  DS_COR_RACA CD_OCUPACAO  \
0    ENSINO FUNDAMENTAL COMPLETO     SOLTEIRO(A)        PARDA         221   
1          ENSINO MÉDIO COMPLETO       CASADO(A)        PARDA         257   
2  ENSINO FUNDAMENTAL INCOMPLETO     SOLTEIRO(A)       BRANCA         411   
3          ENSINO MÉDIO COMPLETO       CASADO(A)        PARDA         601   
4          ENSINO MÉDIO COMPLETO     SOLTEIRO(A)        PARDA         931   
5    ENSINO FUNDAMENTAL COMPLETO       CASADO(A)        PARDA         257   
6          ENSINO MÉDIO COMPLETO     SOLTEIRO(A)       BRANCA         999   
7          ENSINO MÉDIO COMPLETO     SOLTEIRO(A)        PARDA         278   
8          ENSINO MÉDIO COMPLETO     SOLTEIRO(A)        PARDA         169   
9          ENSINO MÉDIO COMPLETO     SOLTEIRO(A)        PARDA         931   

                                      DS_OCUPACAO VR_DESPESA_MAX_CAMPANHA  \
0                                         MOTOBOY                19368.44   
1                                      EMPRESÁRIO                70399.54   
2     VENDEDOR DE COMÉRCIO VAREJISTA E ATACADISTA                94932.72   
3                                      AGRICULTOR               123077.42   
4  ESTUDANTE, BOLSISTA, ESTAGIÁRIO E ASSEMELHADOS                34383.77   
5                                      EMPRESÁRIO                34383.77   
6                                          OUTROS                15842.79   
7                                        VEREADOR                12307.75   
8                                     COMERCIANTE                24211.47   
9  ESTUDANTE, BOLSISTA, ESTAGIÁRIO E AS

In [ ]:
dados_candidatos.sample(10)

NR_TURNO  CD_ELEICAO                 NM_UE  DS_CARGO  SQ_CANDIDATO  \
2797         1         426             ARAPIRACA  VEREADOR   20000801788   
434          1         426           ÁGUA BRANCA  PREFEITO   20000973265   
7513         1         426             ARAPIRACA  VEREADOR   20000876544   
2322         1         426             TAQUARANA  VEREADOR   20000959835   
5044         1         426  SENADOR RUI PALMEIRA  VEREADOR   20000848137   
1150         1         426              OLIVENÇA  VEREADOR   20000950726   
1345         1         426   PASSO DE CAMARAGIBE  VEREADOR   20000699715   
6141         1         426                PENEDO  VEREADOR   20000868858   
3958         1         426  MATRIZ DE CAMARAGIBE  VEREADOR   20001000428   
5851         1         426         PAULO JACINTO  VEREADOR   20001262495   

      NR_CANDIDATO                        NM_CANDIDATO    NM_URNA_CANDIDATO  \
2797         15789                SILVANIA NUNES LEITE    SILVANIA DA SAUDE   
434             17           ADRIANA BARBOSA MAGALHAES         ADRIANA ZUZA   
7513         11444             PEDRO FERREIRA DA SILVA     PEDRO MANGABEIRA   
2322         15123               MARCOS ANDRE DA SILVA  MARQUINHOS DO DINDA   
5044         15999                   EUDES SILVA MATOS          EUDES MATOS   
1150         10777                 LUCAS SILVA DE MELO           LUCAS DUDA   
1345         15444           ANTONIO BEZERRA DE ARAUJO       TONHO DA KOMBI   
6141         12369                  JOSÉ LEILDO MATIAS         BINHO MATIAS   
3958         20777       MARCIEL DOS SANTOS CAVALCANTE   MARCIEL DO CELULAR   
5851         25999  VITORIA RODRIGUES CORREIA DE SOUZA      VITÓRIA CORREIA   

     DS_SITUACAO_CANDIDATURA DS_DETALHE_SITUACAO_CAND  ...  \
2797                    APTO                 DEFERIDO  ...   
434                     APTO                 DEFERIDO  ...   
7513                    APTO                 DEFERIDO  ...   
2322                    APTO                 DEFERIDO  ...   
5044                    APTO                 DEFERIDO  ...   
1150                    APTO                 DEFERIDO  ...   
1345                    APTO                 DEFERIDO  ...   
6141                    APTO                 DEFERIDO  ...   
3958                    APTO                 DEFERIDO  ...   
5851                    APTO                 DEFERIDO  ...   

                  DS_GRAU_INSTRUCAO DS_ESTADO_CIVIL  DS_COR_RACA CD_OCUPACAO  \
2797              SUPERIOR COMPLETO   DIVORCIADO(A)        PARDA         298   
434               SUPERIOR COMPLETO        VIÚVO(A)       BRANCA         257   
7513    ENSINO FUNDAMENTAL COMPLETO     SOLTEIRO(A)        PARDA         109   
2322          ENSINO MÉDIO COMPLETO     SOLTEIRO(A)       BRANCA         601   
5044          ENSINO MÉDIO COMPLETO       CASADO(A)        PARDA         601   
1150            SUPERIOR INCOMPLETO     SOLTEIRO(A)       BRANCA         931   
1345                   LÊ E ESCREVE     SOLTEIRO(A)        PARDA         531   
6141  ENSINO FUNDAMENTAL INCOMPLETO       CASADO(A)        PARDA         531   
3958          ENSINO MÉDIO COMPLETO       CASADO(A)        PARDA         999   
5851            SUPERIOR INCOMPLETO   DIVORCIADO(A)        PARDA         931   

                                            DS_OCUPACAO  \
2797                         SERVIDOR PÚBLICO MUNICIPAL   
434                                          EMPRESÁRIO   
7513                      AGENTE DE SAÚDE E SANITARISTA   
2322                                         AGRICULTOR   
5044                                         AGRICULTOR   
1150     ESTUDANTE, BOLSISTA, ESTAGIÁRIO E ASSEMELHADOS   
1345  MOTORISTA DE VEÍCULOS DE TRANSPORTE COLETIVO D...   
6141  MOTORISTA DE VEÍCULOS DE TRANSPORTE COLETIVO D...   
3958                                             OUTROS   
5851     ESTUDANTE, BOLSISTA, ESTAGIÁRIO E ASSEMELHADOS   

     VR_DESPESA_MAX_CAMPANHA DS_SIT_TOT_TURNO  ST_REELEICAO  \
2797                94

#### Manipulando os dados

##### Verificar valores Ausentes

In [ ]:
#Valores não-nulos por coluna
dados_candidatos.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 7573 entries, 0 to 7582
Data columns (total 24 columns):
 #   Column                      Non-Null Count  Dtype  
---  ------                      --------------  -----  
 0   NR_TURNO                    7573 non-null   int64  
 1   CD_ELEICAO                  7573 non-null   int64  
 2   NM_UE                       7573 non-null   object 
 3   DS_CARGO                    7573 non-null   object 
 4   SQ_CANDIDATO                7573 non-null   int64  
 5   NR_CANDIDATO                7573 non-null   int64  
 6   NM_CANDIDATO                7573 non-null   object 
 7   NM_URNA_CANDIDATO           7573 non-null   object 
 8   DS_SITUACAO_CANDIDATURA     7573 non-null   object 
 9   DS_DETALHE_SITUACAO_CAND    7573 non-null   object 
 10  SG_PARTIDO                  7573 non-null   object 
 11  DT_NASCIMENTO               7572 non-null   object 
 12  NR_IDADE_DATA_POSSE         7572 non-null   float64
 13  DS_GENERO                   7573 

In [ ]:
#Número de valores ausentes para cada coluna
dados_candidatos.isnull().sum()

NR_TURNO                      0
CD_ELEICAO                    0
NM_UE                         0
DS_CARGO                      0
SQ_CANDIDATO                  0
NR_CANDIDATO                  0
NM_CANDIDATO                  0
NM_URNA_CANDIDATO             0
DS_SITUACAO_CANDIDATURA       0
DS_DETALHE_SITUACAO_CAND      0
SG_PARTIDO                    0
DT_NASCIMENTO                 1
NR_IDADE_DATA_POSSE           1
DS_GENERO                     0
DS_GRAU_INSTRUCAO             0
DS_ESTADO_CIVIL               0
DS_COR_RACA                   0
CD_OCUPACAO                   0
DS_OCUPACAO                   0
VR_DESPESA_MAX_CAMPANHA       0
DS_SIT_TOT_TURNO              0
ST_REELEICAO                  0
DS_SITUACAO_CANDIDATO_URNA    0
ST_CANDIDATO_INSERIDO_URNA    0
dtype: int64

**Conclusão**: não há valores faltantes nessa tabela

##### Procurando inconsistèncias nos dados

In [ ]:
# verificando os valores únicos na tabela e se realmente so existe o 1º turno após o filtro
dados_candidatos.nunique()

NR_TURNO                         1
CD_ELEICAO                       1
NM_UE                          102
DS_CARGO                         3
SQ_CANDIDATO                  7573
NR_CANDIDATO                  1432
NM_CANDIDATO                  7471
NM_URNA_CANDIDATO             7293
DS_SITUACAO_CANDIDATURA          2
DS_DETALHE_SITUACAO_CAND         9
SG_PARTIDO                      30
DT_NASCIMENTO                 5977
NR_IDADE_DATA_POSSE             64
DS_GENERO                        3
DS_GRAU_INSTRUCAO                9
DS_ESTADO_CIVIL                  6
DS_COR_RACA                      7
CD_OCUPACAO                    154
DS_OCUPACAO                    154
VR_DESPESA_MAX_CAMPANHA        124
DS_SIT_TOT_TURNO                 7
ST_REELEICAO                     3
DS_SITUACAO_CANDIDATO_URNA       6
ST_CANDIDATO_INSERIDO_URNA       2
dtype: int64

In [ ]:
dados_candidatos.shape # Vendo a quantidade de linhas e colunas na tabela

(7573, 24)

In [ ]:
# O código e nr do turno não serão nescessarios
dados_candidatos.drop(columns=['CD_ELEICAO', 'NR_TURNO', 'DS_SITUACAO_CANDIDATURA'], inplace=True)

In [ ]:
dados_candidatos.columns.values # Vendo se realmente as colunas sumiram

array(['NM_UE', 'DS_CARGO', 'SQ_CANDIDATO', 'NR_CANDIDATO',
       'NM_CANDIDATO', 'NM_URNA_CANDIDATO', 'DS_DETALHE_SITUACAO_CAND',
       'SG_PARTIDO', 'DT_NASCIMENTO', 'NR_IDADE_DATA_POSSE', 'DS_GENERO',
       'DS_GRAU_INSTRUCAO', 'DS_ESTADO_CIVIL', 'DS_COR_RACA',
       'CD_OCUPACAO', 'DS_OCUPACAO', 'VR_DESPESA_MAX_CAMPANHA',
       'DS_SIT_TOT_TURNO', 'ST_REELEICAO', 'DS_SITUACAO_CANDIDATO_URNA',
       'ST_CANDIDATO_INSERIDO_URNA'], dtype=object)

In [ ]:
dados_candidatos['DS_CARGO'].unique() # Verificando os cargos presentes na tabela 

array(['VEREADOR', 'PREFEITO', 'VICE-PREFEITO'], dtype=object)

* Criado filtro com os vice-prefeitos tirados da tabela

In [ ]:
dados_candidatos['DS_CARGO'].value_counts() # Observando o número de candidatos para cada cargo

VEREADOR         6887
VICE-PREFEITO     348
PREFEITO          338
Name: DS_CARGO, dtype: int64

In [ ]:
dados_candidatos['NM_CANDIDATO'].value_counts() # Verificando se há candidatos com nomes iguais

MARIA JOSÉ DA SILVA                        4
MARIA APARECIDA DOS SANTOS                 4
JOSÉ CARLOS DOS SANTOS                     4
JOSE CICERO DA SILVA                       4
JOSÉ ROBERTO DOS SANTOS                    4
                                          ..
ADRIANA ALVES BEZERRA                      1
MARIA CRISTINA FERREIRA DE MENDONÇA        1
MARIA FELIX SILVA DOS SANTOS               1
WADEILDO JOSE GOMES VASCONCELOS BEZERRA    1
SIDNEY CONDE PLACIDO                       1
Name: NM_CANDIDATO, Length: 7471, dtype: int64

In [ ]:
# Como em teoria não pode haver dois candidatos com mesmo número para o cargo e cidade iguais
dados_candidatos[['NM_UE','NR_CANDIDATO', 'DS_CARGO']].value_counts() # OBS: Vice-prefeito possui o mesmo nº que o prefeito

NM_UE              NR_CANDIDATO  DS_CARGO     
PORTO CALVO        55            PREFEITO         3
PARICONHA          15            VICE-PREFEITO    2
SÃO BRÁS           20            VICE-PREFEITO    2
PARICONHA          15            PREFEITO         2
SANTANA DO MUNDAÚ  33111         VEREADOR         2
                                                 ..
JEQUIÁ DA PRAIA    45            PREFEITO         1
                   40            VICE-PREFEITO    1
                                 PREFEITO         1
                   11            PREFEITO         1
ÁGUA BRANCA        90999         VEREADOR         1
Length: 7530, dtype: int64

In [ ]:
dados_candidatos[['NR_CANDIDATO', 'NM_UE', 'NM_CANDIDATO']].value_counts()

NR_CANDIDATO  NM_UE                 NM_CANDIDATO                   
20            ATALAIA               CAMYLA BRASIL PARANHOS LIMA        2
15            ÁGUA BRANCA           MARCELO SANDES GOMES               2
28555         MATRIZ DE CAMARAGIBE  EDLEIDE SANTOS DA SILVA            2
15            PARICONHA             ALVONI FEITOSA DA SILVA            2
10            ARAPIRACA             EVERTON SANTIAGO MAIA              1
                                                                      ..
13999         SANTANA DO IPANEMA    WYLLYANNE STEFFANNE LIMA FARIAS    1
              PALMEIRA DOS ÍNDIOS   JEFFERSON PONTES DOS SANTOS        1
              MINADOR DO NEGRÃO     IARA SOARES DE OLIVEIRA            1
              MARECHAL DEODORO      JOSE JORGE DOS SANTOS              1
90999         ÁGUA BRANCA           ADENILSON DE ARAÚJO DE SOUZA       1
Length: 7569, dtype: int64

In [ ]:
dados_candidatos['SG_PARTIDO'].unique() # Verificando os partidos presentes na tabela

array(['PTB', 'DEM', 'PV', 'PDT', 'PP', 'SOLIDARIEDADE', 'REPUBLICANOS',
       'MDB', 'PT', 'PSD', 'AVANTE', 'PSDB', 'PRTB', 'PMN', 'PSB', 'PTC',
       'PATRIOTA', 'PSC', 'PODE', 'PSL', 'PROS', 'CIDADANIA', 'PC do B',
       'PL', 'PSOL', 'REDE', 'DC', 'UP', 'PSTU', 'PCB'], dtype=object)

In [ ]:
dados_candidatos['DS_GRAU_INSTRUCAO'].unique() # Verificando a escolaridade dos candidatos presentes na tabela

array(['ENSINO FUNDAMENTAL COMPLETO', 'ENSINO MÉDIO COMPLETO',
       'ENSINO FUNDAMENTAL INCOMPLETO', 'SUPERIOR INCOMPLETO',
       'LÊ E ESCREVE', 'SUPERIOR COMPLETO', 'ENSINO MÉDIO INCOMPLETO',
       'NÃO DIVULGÁVEL', 'ANALFABETO'], dtype=object)

In [ ]:
dados_candidatos['DS_ESTADO_CIVIL'].unique() # Verificando os estados cívis presentes na tabela

array(['SOLTEIRO(A)', 'CASADO(A)', 'VIÚVO(A)', 'DIVORCIADO(A)',
       'SEPARADO(A) JUDICIALMENTE', 'NÃO DIVULGÁVEL'], dtype=object)

In [ ]:
dados_candidatos['DS_COR_RACA'].unique() # Verificando as cor/raca presentes na tabela

array(['PARDA', 'BRANCA', 'PRETA', 'NÃO INFORMADO', 'AMARELA', 'INDÍGENA',
       'NÃO DIVULGÁVEL'], dtype=object)

In [ ]:
dados_candidatos['DS_OCUPACAO'].unique() # Verificando as ocupações presentes na tabela

array(['MOTOBOY', 'EMPRESÁRIO',
       'VENDEDOR DE COMÉRCIO VAREJISTA E ATACADISTA', 'AGRICULTOR',
       'ESTUDANTE, BOLSISTA, ESTAGIÁRIO E ASSEMELHADOS', 'OUTROS',
       'VEREADOR', 'COMERCIANTE', 'APOSENTADO (EXCETO SERVIDOR PÚBLICO)',
       'AGENTE ADMINISTRATIVO', 'DONA DE CASA',
       'VENDEDOR PRACISTA, REPRESENTANTE, CAIXEIRO-VIAJANTE E ASSEMELHADOS',
       'TÉCNICO EM AGRONOMIA E AGRIMENSURA', 'ADMINISTRADOR',
       'ASSISTENTE SOCIAL', 'REPRESENTANTE COMERCIAL', 'ADVOGADO',
       'JORNALISTA E REDATOR', 'TRABALHADOR RURAL', 'VIGILANTE',
       'SERVIDOR PÚBLICO FEDERAL', 'SERVIDOR PÚBLICO MUNICIPAL',
       'DECORADOR',
       'MOTORISTA DE VEÍCULOS DE TRANSPORTE COLETIVO DE PASSAGEIROS',
       'PROFESSOR DE ENSINO FUNDAMENTAL', 'PRODUTOR AGROPECUÁRIO',
       'PEDAGOGO', 'POLICIAL MILITAR', 'CONTADOR', 'MOTORISTA PARTICULAR',
       'ENGENHEIRO', 'ZOOTECNISTA', 'SERVIDOR PÚBLICO ESTADUAL',
       'FISIOTERAPEUTA E TERAPEUTA OCUPACIONAL',
       'AGENTE DE SAÚDE E SAN

In [ ]:
dados_candidatos['DS_OCUPACAO'].value_counts() 

OUTROS                                                  1285
AGRICULTOR                                              1013
SERVIDOR PÚBLICO MUNICIPAL                               626
VEREADOR                                                 526
COMERCIANTE                                              490
                                                        ... 
MODELO                                                     1
LEITURISTA                                                 1
PETROLEIRO                                                 1
EMBALADOR, EMPACOTADOR E ASSEMELHADOS                      1
MARINHEIRO CIVIL, CANOEIRO, EMBARCADO E ASSEMELHADOS       1
Name: DS_OCUPACAO, Length: 154, dtype: int64

In [ ]:
dados_candidatos['DS_SIT_TOT_TURNO'].unique() # Verificando o status dos candidatos ao fim do 1º turno presentes na tabela

array(['NÃO ELEITO', 'ELEITO POR QP', 'SUPLENTE', '#NULO#', 'ELEITO',
       'ELEITO POR MÉDIA', '2º TURNO'], dtype=object)

##### Verficar o número total de municipios presentes

In [ ]:
#Calculando o número de municipios e o numero de candidatos por municipio
dados_candidatos[['NM_UE']].value_counts()

NM_UE                
MACEIÓ                   619
ARAPIRACA                376
UNIÃO DOS PALMARES       261
MARECHAL DEODORO         186
SÃO MIGUEL DOS CAMPOS    165
                        ... 
SENADOR RUI PALMEIRA      27
QUEBRANGULO               27
BELO MONTE                24
PINDOBA                   23
CACIMBINHAS               21
Length: 102, dtype: int64

Conclusão: 
* Há 102 municipios quantificados, ou seja, todos os municipios do estado.



#### Outros filtros

In [ ]:
# filtrando por vereador e prefeito
filtro_no_vice = dados_candidatos.loc[dados_candidatos['DS_CARGO'] != 'VICE-PREFEITO']

In [ ]:
filtro_no_vice.shape

(7225, 24)

In [ ]:
# Filtro para pegar dados de um municipo
municipio = 'ARAPIRACA'
mun_dados_cand = dados_candidatos.loc[(dados_candidatos['NM_UE'] == municipio)]

### Tabela 2 - Votos recebidos por cada cadidato - 1º turno

#### Atributos da tabela

Pricipais atributos do dataset: 

* str - **CD_ELEICAO** - código da eleição
* str - **DS_CARGO** = Prefeito ou Vereador
* str - **SG_UE** - número do municipio
* int - **SQ_CANDIDATO** - número sequencial gerado pelos sistemas eleitorais
* str - **NM_UE** - nome da unidade eleitoral do candidato
* str -  **NM_CANDIDATO** - nome do cadidato
* int -   **nr_turno** = o turno em que foram resgistrados os dados
* int -  **nr_zona** - número da zona eleitoral
* str  **sg_partido** = sigla do partido do cadidato
* int - **CD_SIT_TOT_TURNO** - código da situação de totalização no turno
* str -  **ds_sit_totalizacao** = eleito, nao eleito e +
* str - **NM_URNA_CANDIDATO** - nome do candidato na urna
* int -  **QT_VOTOS_NOMINAIS** = Quantidade de votos dedicados a cada candidato por Zona Eleitoral


**Quantidade de linhas**: 9337 para o estado de Alagoas

**Quantidade de Municipios**: 102, ou seja, todos os municípios do Estado

Não foram encontrados valores ausentes na tabela

#### Lendo a Tabela

In [ ]:
#Tabela que contem a quantidade de votos que cada canditado recebeu por zona na eleição de 2020
#OBS: algumas cidades tem mais de uma zona eleitoral
dados_votacao_zona = pd.read_csv('/content/drive/My Drive/Visualização Computacional/votacao_candidato_munzona_2020_AL.csv', sep=";", encoding='latin-1')

In [ ]:
# Pegando o 1º turno das eleições ordinarias
dados_votacao = dados_votacao_zona.loc[(dados_votacao_zona.CD_ELEICAO == 426)]

Como algumas cidades como Maceio e Arapiraca possuem mais de uma zona eleitoral é nescessario tratar os dados

#### Visualizando a Tabela

In [ ]:
dados_votacao.head(10)

DT_GERACAO HH_GERACAO  ANO_ELEICAO  CD_TIPO_ELEICAO    NM_TIPO_ELEICAO  \
0  12/09/2022   03:56:30         2020                2  Eleição Ordinária   
1  12/09/2022   03:56:30         2020                2  Eleição Ordinária   
2  12/09/2022   03:56:30         2020                2  Eleição Ordinária   
3  12/09/2022   03:56:30         2020                2  Eleição Ordinária   
4  12/09/2022   03:56:30         2020                2  Eleição Ordinária   
5  12/09/2022   03:56:30         2020                2  Eleição Ordinária   
6  12/09/2022   03:56:30         2020                2  Eleição Ordinária   
7  12/09/2022   03:56:30         2020                2  Eleição Ordinária   
8  12/09/2022   03:56:30         2020                2  Eleição Ordinária   
9  12/09/2022   03:56:30         2020                2  Eleição Ordinária   

   NR_TURNO  CD_ELEICAO                DS_ELEICAO  DT_ELEICAO TP_ABRANGENCIA  \
0         1         426  ELEIÇÕES MUNICIPAIS 2020  15/11/2020              M   
1         1         426  ELEIÇÕES MUNICIPAIS 2020  15/11/2020              M   
2         1         426  ELEIÇÕES MUNICIPAIS 2020  15/11/2020              M   
3         1         426  ELEIÇÕES MUNICIPAIS 2020  15/11/2020              M   
4         1         426  ELEIÇÕES MUNICIPAIS 2020  15/11/2020              M   
5         1         426  ELEIÇÕES MUNICIPAIS 2020  15/11/2020              M   
6         1         426  ELEIÇÕES MUNICIPAIS 2020  15/11/2020              M   
7         1         426  ELEIÇÕES MUNICIPAIS 2020  15/11/2020              M   
8         1         426  ELEIÇÕES MUNICIPAIS 2020  15/11/2020              M   
9         1         426  ELEIÇÕES MUNICIPAIS 2020  15/11/2020              M   

   ... NR_PARTIDO  SG_PARTIDO                        NM_PARTIDO  SQ_COLIGACAO  \
0  ...         15         MDB  Movimento Democrático Brasileiro   20000075552   
1  ...         15         MDB  Movimento Democrático Brasileiro   20000075552   
2  ...         15         MDB  Movimento Democrático Brasileiro   20000075552   
3  ...         70      AVANTE                            AVANTE   20000075658   
4  ...         70      AVANTE                            AVANTE   20000075702   
5  ...         11          PP                     PROGRESSISTAS   20000088522   
6  ...         25         DEM                        Democratas   20000106784   
7  ...         40         PSB     Partido Socialista Brasileiro   20000106791   
8  ...         14         PTB    Partido Trabalhista Brasileiro   20000130738   
9  ...         11          PP                     PROGRESSISTAS   20000144816   

      NM_COLIGACAO  DS_COMPOSICAO_COLIGACAO  CD_SIT_TOT_TURNO  \
0  PARTIDO ISOLADO                      MDB                 2   
1  PARTIDO ISOLADO                      MDB                 3   
2  PARTIDO ISOLADO                      MDB                 5   
3  PARTIDO ISOLADO                   AVANTE                 4   
4  PARTIDO ISOLADO                   AVANTE                 4   
5  PARTIDO ISOLADO                       PP                 5   
6  PARTIDO ISOLADO                      DEM                 5   
7  PARTIDO ISOLADO                      PSB                 4   
8  PARTIDO ISOLADO                      PTB                 2   
9  PARTIDO ISOLADO                       PP                 5   

   DS_SIT_TOT_TURNO  ST_VOTO_EM_TRANSITO  QT_VOTOS_NOMINAIS  
0     ELEITO POR QP                    N                590  
1  ELEITO POR MÉDIA                    N                544  
2          SUPLENTE                    N                468  
3        NÃO ELEITO                    N                645  
4        NÃO ELEITO                    N                  9  
5          SUPLENTE                    N                  0  
6          SUPLENTE                    N                  1  
7        NÃO ELEITO                    N                  0  
8     ELEITO POR QP                    N                299  
9          SUPLENTE                    N      

In [ ]:
dados_votacao.sample(10)

DT_GERACAO HH_GERACAO  ANO_ELEICAO  CD_TIPO_ELEICAO    NM_TIPO_ELEICAO  \
2306  12/09/2022   03:56:30         2020                2  Eleição Ordinária   
8063  12/09/2022   03:56:30         2020                2  Eleição Ordinária   
1208  12/09/2022   03:56:30         2020                2  Eleição Ordinária   
6599  12/09/2022   03:56:30         2020                2  Eleição Ordinária   
308   12/09/2022   03:56:30         2020                2  Eleição Ordinária   
3236  12/09/2022   03:56:30         2020                2  Eleição Ordinária   
4419  12/09/2022   03:56:30         2020                2  Eleição Ordinária   
2658  12/09/2022   03:56:30         2020                2  Eleição Ordinária   
7788  12/09/2022   03:56:30         2020                2  Eleição Ordinária   
4097  12/09/2022   03:56:30         2020                2  Eleição Ordinária   

      NR_TURNO  CD_ELEICAO                DS_ELEICAO  DT_ELEICAO  \
2306         1         426  ELEIÇÕES MUNICIPAIS 2020  15/11/2020   
8063         1         426  ELEIÇÕES MUNICIPAIS 2020  15/11/2020   
1208         1         426  ELEIÇÕES MUNICIPAIS 2020  15/11/2020   
6599         1         426  ELEIÇÕES MUNICIPAIS 2020  15/11/2020   
308          1         426  ELEIÇÕES MUNICIPAIS 2020  15/11/2020   
3236         1         426  ELEIÇÕES MUNICIPAIS 2020  15/11/2020   
4419         1         426  ELEIÇÕES MUNICIPAIS 2020  15/11/2020   
2658         1         426  ELEIÇÕES MUNICIPAIS 2020  15/11/2020   
7788         1         426  ELEIÇÕES MUNICIPAIS 2020  15/11/2020   
4097         1         426  ELEIÇÕES MUNICIPAIS 2020  15/11/2020   

     TP_ABRANGENCIA  ... NR_PARTIDO    SG_PARTIDO  \
2306              M  ...         13            PT   
8063              M  ...         33           PMN   
1208              M  ...         11            PP   
6599              M  ...         55           PSD   
308               M  ...         15           MDB   
3236              M  ...         10  REPUBLICANOS   
4419              M  ...         10  REPUBLICANOS   
2658              M  ...         10  REPUBLICANOS   
7788              M  ...         40           PSB   
4097              M  ...         11            PP   

                            NM_PARTIDO  SQ_COLIGACAO     NM_COLIGACAO  \
2306         Partido dos Trabalhadores   20000139572  PARTIDO ISOLADO   
8063   Partido da Mobilização Nacional   20000145766  PARTIDO ISOLADO   
1208                     PROGRESSISTAS   20000110663  PARTIDO ISOLADO   
6599        Partido Social Democrático   20000154850  PARTIDO ISOLADO   
308   Movimento Democrático Brasileiro   20000064883  PARTIDO ISOLADO   
3236                      REPUBLICANOS   20000123562  PARTIDO ISOLADO   
4419                      REPUBLICANOS   20000158847  PARTIDO ISOLADO   
2658                      REPUBLICANOS   20000135866  PARTIDO ISOLADO   
7788     Partido Socialista Brasileiro   20000075172  PARTIDO ISOLADO   
4097                     PROGRESSISTAS   20000144004  PARTIDO ISOLADO   

      DS_COMPOSICAO_COLIGACAO  CD_SIT_TOT_TURNO  DS_SIT_TOT_TURNO  \
2306                       PT                 4        NÃO ELEITO   
8063                      PMN                 4        NÃO ELEITO   
1208                       PP                 5          SUPLENTE   
6599                      PSD                 2     ELEITO POR QP   
308                       MDB                 5          SUPLENTE   
3236             REPUBLICANOS                 5          SUPLENTE   
4419             REPUBLICANOS                 5          SUPLENTE   
2658             REPUBLICANOS                 5          SUPLENTE   
7788                      PSB                 3  ELEITO POR MÉDIA   
4097                       PP                 2     ELEITO POR QP   

      ST_VOTO_EM_TRANSITO  QT_VOTOS_NOMINAIS  
2306                    N                 55  
8063                    N                  6  
1208                    N                 73  
6599                    N               

#### Manipulando os Dados

##### Verificar valores Ausentes

In [ ]:
#Valores não-nulos por coluna
dados_votacao.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 9337 entries, 0 to 9349
Data columns (total 38 columns):
 #   Column                    Non-Null Count  Dtype 
---  ------                    --------------  ----- 
 0   DT_GERACAO                9337 non-null   object
 1   HH_GERACAO                9337 non-null   object
 2   ANO_ELEICAO               9337 non-null   int64 
 3   CD_TIPO_ELEICAO           9337 non-null   int64 
 4   NM_TIPO_ELEICAO           9337 non-null   object
 5   NR_TURNO                  9337 non-null   int64 
 6   CD_ELEICAO                9337 non-null   int64 
 7   DS_ELEICAO                9337 non-null   object
 8   DT_ELEICAO                9337 non-null   object
 9   TP_ABRANGENCIA            9337 non-null   object
 10  SG_UF                     9337 non-null   object
 11  SG_UE                     9337 non-null   int64 
 12  NM_UE                     9337 non-null   object
 13  CD_MUNICIPIO              9337 non-null   int64 
 14  NM_MUNICIPIO            

In [ ]:
#Número de valores ausentes para cada coluna
dados_votacao.isnull().sum()

DT_GERACAO                  0
HH_GERACAO                  0
ANO_ELEICAO                 0
CD_TIPO_ELEICAO             0
NM_TIPO_ELEICAO             0
NR_TURNO                    0
CD_ELEICAO                  0
DS_ELEICAO                  0
DT_ELEICAO                  0
TP_ABRANGENCIA              0
SG_UF                       0
SG_UE                       0
NM_UE                       0
CD_MUNICIPIO                0
NM_MUNICIPIO                0
NR_ZONA                     0
CD_CARGO                    0
DS_CARGO                    0
SQ_CANDIDATO                0
NR_CANDIDATO                0
NM_CANDIDATO                0
NM_URNA_CANDIDATO           0
NM_SOCIAL_CANDIDATO         0
CD_SITUACAO_CANDIDATURA     0
DS_SITUACAO_CANDIDATURA     0
CD_DETALHE_SITUACAO_CAND    0
DS_DETALHE_SITUACAO_CAND    0
TP_AGREMIACAO               0
NR_PARTIDO                  0
SG_PARTIDO                  0
NM_PARTIDO                  0
SQ_COLIGACAO                0
NM_COLIGACAO                0
DS_COMPOSI

**Conclusão**: não há valores faltantes nessa tabela

##### Verficar o número total de municipios presentes

In [ ]:
#Calculando o número de municipios
dados_votacao[['NM_UE']].nunique()

NM_UE    102
dtype: int64

Conclusão: 
* Há 102 municipios quantificados, ou seja, todos os municipios do estado.



##### Procurando inconsistèncias nos dados

In [ ]:
# verificando os valores únicos na tabela e se realmente so existe o 1º turno nela após o filtro
dados_votacao.nunique()

DT_GERACAO                     1
HH_GERACAO                     1
ANO_ELEICAO                    1
CD_TIPO_ELEICAO                1
NM_TIPO_ELEICAO                1
NR_TURNO                       1
CD_ELEICAO                     1
DS_ELEICAO                     1
DT_ELEICAO                     1
TP_ABRANGENCIA                 1
SG_UF                          1
SG_UE                        102
NM_UE                        102
CD_MUNICIPIO                 102
NM_MUNICIPIO                 102
NR_ZONA                       42
CD_CARGO                       2
DS_CARGO                       2
SQ_CANDIDATO                6811
NR_CANDIDATO                1369
NM_CANDIDATO                6744
NM_URNA_CANDIDATO           6595
NM_SOCIAL_CANDIDATO            1
CD_SITUACAO_CANDIDATURA        1
DS_SITUACAO_CANDIDATURA        1
CD_DETALHE_SITUACAO_CAND       3
DS_DETALHE_SITUACAO_CAND       3
TP_AGREMIACAO                  2
NR_PARTIDO                    30
SG_PARTIDO                    30
NM_PARTIDO

In [ ]:
dados_votacao.shape[0] # verificando o número de linhas na tabela

9337

In [ ]:
dados_votacao['NM_UE'].unique() # Verficando se está tudo certo com a string do municipio

array(['BATALHA', 'MARAVILHA', 'VIÇOSA', 'ESTRELA DE ALAGOAS',
       'OURO BRANCO', 'JACARÉ DOS HOMENS', 'UNIÃO DOS PALMARES',
       'SANTANA DO MUNDAÚ', 'DELMIRO GOUVEIA', 'PIRANHAS',
       'OLHO D ÁGUA DO CASADO', 'GIRAU DO PONCIANO',
       'SENADOR RUI PALMEIRA', 'TEOTÔNIO VILELA', 'PORTO DE PEDRAS',
       'PARIPUEIRA', 'SÃO MIGUEL DOS MILAGRES', 'PORTO REAL DO COLÉGIO',
       'SANTANA DO IPANEMA', 'MATRIZ DE CAMARAGIBE', 'TANQUE D ARCA',
       'SÃO JOSÉ DA TAPERA', 'CRAÍBAS', 'SÃO BRÁS', 'MACEIÓ', 'CAPELA',
       'PIAÇABUÇU', 'PENEDO', 'ATALAIA', 'PASSO DE CAMARAGIBE',
       'SÃO LUÍS DO QUITUNDE', 'OLIVENÇA', 'LIMOEIRO DE ANADIA',
       'CARNEIROS', 'CANAPI', 'MATA GRANDE', 'MARECHAL DEODORO',
       'BOCA DA MATA', 'ANADIA', 'CAMPO ALEGRE', 'BARRA DE SÃO MIGUEL',
       'MAJOR ISIDORO', 'BARRA DE SANTO ANTÔNIO', 'SATUBA', 'PORTO CALVO',
       'SANTA LUZIA DO NORTE', 'JUNDIÁ', 'RIO LARGO', 'COQUEIRO SECO',
       'MARAGOGI', 'JAPARATINGA', 'JARAMATAIA', 'FELIZ DESERTO',

In [ ]:
dados_votacao['DS_CARGO'].unique() # Vericando os cargos presentes na tabela

array(['Vereador', 'Prefeito'], dtype=object)

In [ ]:
dados_votacao['SQ_CANDIDATO'].unique() 

array([20000778663, 20000778664, 20000778670, ..., 20000702818,
       20001090169, 20001090894])

In [ ]:
dados_votacao['NR_CANDIDATO'].unique().take([110,10]) # Vericando os cargos presentes na tabela

array([90111, 11555])

In [ ]:
dados_votacao['NM_URNA_CANDIDATO'].unique() # 

array(['FABIANO MANDIM', 'ALDO PROFESSOR', 'PEPEU', ..., 'AVANELE',
       'ZÉ DA NÍ', 'MAURICIO DELLA VERGHAH'], dtype=object)

In [ ]:
dados_votacao['DS_DETALHE_SITUACAO_CAND'].unique()

array(['DEFERIDO', 'DEFERIDO COM RECURSO', 'PENDENTE DE JULGAMENTO'],
      dtype=object)

In [ ]:
dados_votacao['DS_DETALHE_SITUACAO_CAND'].value_counts()

DEFERIDO                  9134
DEFERIDO COM RECURSO       202
PENDENTE DE JULGAMENTO       1
Name: DS_DETALHE_SITUACAO_CAND, dtype: int64

In [ ]:
dados_votacao['TP_AGREMIACAO'].unique()

array(['Partido isolado', 'Coligação'], dtype=object)

In [ ]:
dados_votacao['SG_PARTIDO'].unique() # Verificando os partidos presentes

array(['MDB', 'AVANTE', 'PP', 'DEM', 'PSB', 'PTB', 'REPUBLICANOS', 'PT',
       'PRTB', 'PSD', 'PDT', 'CIDADANIA', 'PROS', 'SOLIDARIEDADE', 'PSL',
       'PSDB', 'PMN', 'PSC', 'REDE', 'PL', 'PC do B', 'PATRIOTA', 'UP',
       'PODE', 'PTC', 'PSTU', 'PSOL', 'PV', 'DC', 'PCB'], dtype=object)

In [ ]:
dados_votacao['DS_SIT_TOT_TURNO'].unique() # o Status do candidato no final do turno

array(['ELEITO POR QP', 'ELEITO POR MÉDIA', 'SUPLENTE', 'NÃO ELEITO',
       'ELEITO', '2º TURNO'], dtype=object)

In [ ]:
dados_votacao['NM_SOCIAL_CANDIDATO'].unique() # Varificando o uso de nome social

array(['#NULO#'], dtype=object)

In [ ]:
dados_votacao['ST_VOTO_EM_TRANSITO'].unique() # Varificando o uso do voto em transito

array(['N'], dtype=object)

In [ ]:
# Como não deveria existir números de candidatos iguais em uma UE poderia ser um criterio para agrupar os dados além do SQ do candidato
dados_votacao[['NM_UE', 'NR_CANDIDATO']].value_counts()

NM_UE            NR_CANDIDATO
MACEIÓ           90005           5
                 90100           5
                 90001           5
                 17000           5
                 90009           5
                                ..
JOAQUIM GOMES    11000           1
                 20              1
                 14              1
JEQUIÁ DA PRAIA  55555           1
ÁGUA BRANCA      90999           1
Length: 6811, dtype: int64

In [ ]:
# Verificando se realmente não há candidatos na mesma cidade com o mesmo número
# Como pode haver mais de uma zona eleitoral então natualmente os candidatos nessas cidades podem aparecer mais de uma vez
a = dados_votacao[['NM_UE', 'NR_CANDIDATO','NM_CANDIDATO']].value_counts().reset_index() # add o nome do candidato para ter certeza /
                                                                                          # que nomes diferentes não sejam agrupados
a

NM_UE  NR_CANDIDATO                       NM_CANDIDATO  0
0              MACEIÓ         90005             JAILTON CAMPOS MIRANDA  5
1              MACEIÓ         90100             NAILTON VITOR DA SILVA  5
2              MACEIÓ         90001        TANIA MABEL ANDRADE BARRÊTO  5
3              MACEIÓ         17000     FLÁVIO ANTONIO MORENO DA SILVA  5
4              MACEIÓ         90009         JANIS JOPLIN SILVA DE LIMA  5
...               ...           ...                                ... ..
6806    JOAQUIM GOMES         11000      CICERO FERREIRA DE LIMA FILHO  1
6807    JOAQUIM GOMES            20      KERNNE PETRINY SOARES DE MELO  1
6808    JOAQUIM GOMES            14            ADRIANO FERREIRA BARROS  1
6809  JEQUIÁ DA PRAIA         55555  DOMICIO PEREIRA DOS SANTOS JUNIOR  1
6810      ÁGUA BRANCA         90999       ADENILSON DE ARAÚJO DE SOUZA  1

[6811 rows x 4 columns]

In [ ]:
# Verifica a quantidade de vezes que cada numero aparece na UE
a[['NM_UE', 'NR_CANDIDATO']].value_counts() # OBs> cada numero deve aparecer apenas 1 vez pois não ha vice prefeito na tabela

NM_UE            NR_CANDIDATO
ANADIA           11              1
PENEDO           10333           1
                 10144           1
                 10123           1
                 10114           1
                                ..
JEQUIÁ DA PRAIA  11333           1
                 11234           1
                 11233           1
                 11222           1
ÁGUA BRANCA      90999           1
Length: 6811, dtype: int64

In [ ]:
dados_votacao['QT_VOTOS_NOMINAIS'].dtypes # Verificando se a qt de votos esta em um tipo númerico

dtype('int64')

In [ ]:
dados_votacao.columns.values # Visualizando as colunas da tabela

array(['DT_GERACAO', 'HH_GERACAO', 'ANO_ELEICAO', 'CD_TIPO_ELEICAO',
       'NM_TIPO_ELEICAO', 'NR_TURNO', 'CD_ELEICAO', 'DS_ELEICAO',
       'DT_ELEICAO', 'TP_ABRANGENCIA', 'SG_UF', 'SG_UE', 'NM_UE',
       'CD_MUNICIPIO', 'NM_MUNICIPIO', 'NR_ZONA', 'CD_CARGO', 'DS_CARGO',
       'SQ_CANDIDATO', 'NR_CANDIDATO', 'NM_CANDIDATO',
       'NM_URNA_CANDIDATO', 'NM_SOCIAL_CANDIDATO',
       'CD_SITUACAO_CANDIDATURA', 'DS_SITUACAO_CANDIDATURA',
       'CD_DETALHE_SITUACAO_CAND', 'DS_DETALHE_SITUACAO_CAND',
       'TP_AGREMIACAO', 'NR_PARTIDO', 'SG_PARTIDO', 'NM_PARTIDO',
       'SQ_COLIGACAO', 'NM_COLIGACAO', 'DS_COMPOSICAO_COLIGACAO',
       'CD_SIT_TOT_TURNO', 'DS_SIT_TOT_TURNO', 'ST_VOTO_EM_TRANSITO',
       'QT_VOTOS_NOMINAIS'], dtype=object)

In [ ]:
# Essas colunas não será nescessarias
dados_votacao.drop(columns=['CD_ELEICAO', 'DT_GERACAO', 'HH_GERACAO', 'ANO_ELEICAO', 'CD_TIPO_ELEICAO',
       'NM_TIPO_ELEICAO', 'DT_ELEICAO', 'SG_UF', 'NM_SOCIAL_CANDIDATO',
       'CD_SITUACAO_CANDIDATURA', 'DS_SITUACAO_CANDIDATURA',
       'CD_DETALHE_SITUACAO_CAND', 'DS_DETALHE_SITUACAO_CAND',
       'TP_AGREMIACAO'], inplace=True)

<ipython-input-297-839a13f203e1>:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dados_votacao.drop(columns=['CD_ELEICAO', 'DT_GERACAO', 'HH_GERACAO', 'ANO_ELEICAO', 'CD_TIPO_ELEICAO',


In [ ]:
dados_votacao.columns.values

array(['NR_TURNO', 'DS_ELEICAO', 'TP_ABRANGENCIA', 'SG_UE', 'NM_UE',
       'CD_MUNICIPIO', 'NM_MUNICIPIO', 'NR_ZONA', 'CD_CARGO', 'DS_CARGO',
       'SQ_CANDIDATO', 'NR_CANDIDATO', 'NM_CANDIDATO',
       'NM_URNA_CANDIDATO', 'NR_PARTIDO', 'SG_PARTIDO', 'NM_PARTIDO',
       'SQ_COLIGACAO', 'NM_COLIGACAO', 'DS_COMPOSICAO_COLIGACAO',
       'CD_SIT_TOT_TURNO', 'DS_SIT_TOT_TURNO', 'ST_VOTO_EM_TRANSITO',
       'QT_VOTOS_NOMINAIS'], dtype=object)

### Tabela 3 - Arrecadação

#### Descrição dos principais atributos

**Pricipais atributos do dataset**: 

* **(int)** - CD_TIPO_ELEICAO  - Código da eleição

* **(int)** - ST_TURNO - O indicativo se prestador de contas teve prestação para 2º turno

* **(int)** - TP_PRESTACAO_CONTAS - Tipo de entregada prestação de contas.

* **(str)** - NM_UE - Nome de Unidade Eleitoral do candidato

* **(str)** - DS_CARGO - cargo do candidado

* **(int)** - NR_CANDIDATO - Número do candidato prestador de conta

* **(str)** - NM_CANDIDATO - Nome completo do candidato

* **(int)** - NR_CPF_CANDIDATO - CPF do candidato registrado na Justiça Eleitor

* **(str)** - SG_PARTIDO - Sigla do partido do candidat

* **(str)** - DS_FONTE_RECEITA - Descrição do tipo de fonte do recurso da doação , informado pelo prestador de contas em relação à doação

* **(str)** - DS_ORIGEM_RECEITA - Descrição do o tipo de origem do recurso, informado pelo prestador de contas em relação à doação

* **(str)** - DS_NATUREZA_RECEITA - Descrição da natureza do tipo espécie do recurso da doação

* **(str)** - DS_ESPECIE_RECEITA - Descrição do tipo de espécie do recurso da doação, quando natureza do recurso for igual a financeira

* **(str)** - DS_ESFERA_PARTIDARIA_DOADOR - Descrição do tipo de esfera partidária do doador. Válido para quando doador 'Órgão partidário' 

* **(str)** - NM_MUNICIPIO_DOADOR - Descrição do município do doador, quando a esfera partidária do doador for municipal.

* **(str)** - DS_RECEITA - Descrição Resumida informada pelo prestador de contas em relação à doação.

* **(str)** - VR_RECEITA - Valor da doação em Reais (R$)

*descrições tirados do pdf que vem junto da tabela*

Quantidade de linhas: 

#### Criando a tabela

In [ ]:
#Tabela com dados sobre a arrecadação para a campanha dos candidatos
colunasT2 = ['CD_ELEICAO', 'ST_TURNO', 'TP_PRESTACAO_CONTAS', 'NM_UE', 'DS_CARGO', 'SQ_CANDIDATO', 'NR_CANDIDATO', 'NM_CANDIDATO', 'NR_CPF_CANDIDATO',
             'SG_PARTIDO', 'DS_FONTE_RECEITA', 'DS_ORIGEM_RECEITA', 'DS_NATUREZA_RECEITA', 'DS_ESPECIE_RECEITA', 'DS_ESFERA_PARTIDARIA_DOADOR',
             'NM_MUNICIPIO_DOADOR', 'DS_RECEITA', 'VR_RECEITA']
dados_receitas = pd.read_csv('/content/drive/My Drive/Visualização Computacional/receitas_candidatos_2020_AL.csv', sep=";", encoding='latin-1',
                             usecols=colunasT2)

In [ ]:
# Filtrando com base no código do 1º turno da eleição ordinaria e se o cadidato esta apto a ir as urnas
dados_receitas = dados_receitas.loc[(dados_receitas['CD_ELEICAO'] == 426)].reset_index(drop=True)

In [ ]:
# Como o valor está escrito com string então deve-se converter para float para calculos posteriores
dados_receitas['VR_RECEITA'] = dados_receitas['VR_RECEITA'].str.replace(',', '.') # troca o , por ponto
dados_receitas['VR_RECEITA'] = dados_receitas['VR_RECEITA'].astype(float) # Convertendo para float
dados_receitas['VR_RECEITA'].unique()

array([ 750.  ,  100.  , 1045.  , ...,  535.  , 1214.39,   28.2 ])

#### Visualizando os Dados

In [ ]:
dados_receitas.head(10)

CD_ELEICAO  ST_TURNO TP_PRESTACAO_CONTAS               NM_UE  DS_CARGO  \
0         426         1               FINAL        BOCA DA MATA  Vereador   
1         426         1               FINAL  UNIÃO DOS PALMARES  Prefeito   
2         426         1               FINAL               PILAR  Prefeito   
3         426         1               FINAL      LAGOA DA CANOA  Vereador   
4         426         1               FINAL      LAGOA DA CANOA  Vereador   
5         426         1               FINAL            PIRANHAS  Vereador   
6         426         1               FINAL             ATALAIA  Prefeito   
7         426         1               FINAL              CAPELA  Vereador   
8         426         1               FINAL           TAQUARANA  Vereador   
9         426         1               FINAL        MAR VERMELHO  Prefeito   

   SQ_CANDIDATO  NR_CANDIDATO                          NM_CANDIDATO  \
0   20001212486         12000              JOSE MAURICIO DOS SANTOS   
1   20001186175            13      SERGIO ROGERIO OLIVEIRA DA SILVA   
2   20000750618            20            RENATO REZENDE ROCHA FILHO   
3   20001050232         43000           EDVANIO DE OLIVEIRA ALMEIDA   
4   20001050229         43123                JEFERSON BORGES TORRES   
5   20001015336         77456       RENATO DOUGLAS RODRIGUES JUNIOR   
6   20000841216            20           CECÍLIA LIMA HERRMANN ROCHA   
7   20000836280         19777  LARISSA ALESSANDRA SANTOS DE ALMEIDA   
8   20000681896         10000                  JOSEFA FARIAS SANTOS   
9   20001042530            11               EMANUEL DA SILVA BARROS   

   NR_CPF_CANDIDATO     SG_PARTIDO DS_FONTE_RECEITA  \
0        6176245427            PDT  OUTROS RECURSOS   
1         861010485             PT  OUTROS RECURSOS   
2        3749271461            PSC  OUTROS RECURSOS   
3       92636411453             PV  OUTROS RECURSOS   
4        7272867493             PV  OUTROS RECURSOS   
5        7585206461  SOLIDARIEDADE  OUTROS RECURSOS   
6        5158296413            PSC  OUTROS RECURSOS   
7        8103441490           PODE  OUTROS RECURSOS   
8       11408576490   REPUBLICANOS  OUTROS RECURSOS   
9        3585555403             PP  OUTROS RECURSOS   

             DS_ORIGEM_RECEITA DS_NATUREZA_RECEITA        DS_ESPECIE_RECEITA  \
0  Recursos de pessoas físicas          FINANCEIRO       Depósito em espécie   
1  Recursos de pessoas físicas          FINANCEIRO  Transferência eletrônica   
2  Recursos de pessoas físicas           ESTIMÁVEL                  Estimado   
3  Recursos de pessoas físicas          FINANCEIRO  Transferência eletrônica   
4  Recursos de pessoas físicas          FINANCEIRO  Transferência eletrônica   
5  Recursos de pessoas físicas           ESTIMÁVEL                  Estimado   
6  Recursos de pessoas físicas           ESTIMÁVEL                  Estimado   
7  Recursos de pessoas físicas           ESTIMÁVEL                  Estimado   
8  Recursos de pessoas físicas           ESTIMÁVEL                  Estimado   
9  Recursos de pessoas físicas           ESTIMÁVEL                  Estimado   

  DS_ESFERA_PARTIDARIA_DOADOR NM_MUNICIPIO_DOADOR  \
0                      #NULO#              #NULO#   
1                      #NULO#              #NULO#   
2                      #NULO#              #NULO#   
3                      #NULO#              #NULO#   
4                      #NULO#              #NULO#   
5                      #NULO#              #NULO#   
6                      #NULO#              #NULO#   
7                      #NULO#              #NULO#   
8                      #NULO#              #NULO#   
9                      #NULO#              #NULO#   

                                          DS_RECEITA  VR_RECEITA  
0                                             #NULO#       750.0  
1                                             #NULO#       100.0  
2  SERVIÇOS DE PANFLETAGEM E/OU ADESIVAÇÃO E/OU M...      1045.0  
3                                 

In [ ]:
dados_receitas.sample(10)

CD_ELEICAO  ST_TURNO TP_PRESTACAO_CONTAS                  NM_UE  \
19880         426         1               FINAL                JACUÍPE   
21721         426         1               FINAL            OURO BRANCO   
11995         426         1               FINAL     COLÔNIA LEOPOLDINA   
4688          426         1               FINAL              ARAPIRACA   
20303         426         1               FINAL              RIO LARGO   
6565          426         1               FINAL                 MACEIÓ   
9697          426         1               FINAL  PORTO REAL DO COLÉGIO   
19342         426         1               FINAL              RIO LARGO   
69            426         1               FINAL              PIAÇABUÇU   
1010          426         1               FINAL               MARAGOGI   

       DS_CARGO  SQ_CANDIDATO  NR_CANDIDATO  \
19880  Vereador   20000947022         14123   
21721  Vereador   20001248469         15222   
11995  Vereador   20000770567         45613   
4688   Prefeito   20000686605            15   
20303  Vereador   20000890157         12444   
6565   Vereador   20000824296         19000   
9697   Vereador   20000686503         15967   
19342  Vereador   20000890154         12110   
69     Prefeito   20000796683            40   
1010   Vereador   20001028400         11777   

                                      NM_CANDIDATO  NR_CPF_CANDIDATO  \
19880                    CAETANO JOSE ALVES JUNIOR        7186448402   
21721                JOSIVALDO AMÂNCIO DE OLIVEIRA        6371499475   
11995  MARIA DAS GRAÇAS LEITE FERREIRA DE OLIVEIRA       69980721472   
4688                 JOSÉ LUCIANO BARBOSA DA SILVA       29668174453   
20303                         IZAQUE PEREIRA SILVA         795537450   
6565                    KELMANN VIEIRA DE OLIVEIRA        2581923482   
9697                    VALDICELIA ALMEIDA SANTANA        4603904495   
19342              JOSÉ ROBERTO FIRMINO DE MENEZES       34808060400   
69                    DALMO MOREIRA SANTANA JÚNIOR       98625640400   
1010                  ANDERSON RODRIGUES DE ARAUJO       13819816402   

      SG_PARTIDO DS_FONTE_RECEITA              DS_ORIGEM_RECEITA  \
19880        PTB  OUTROS RECURSOS  Recursos de outros candidatos   
21721        MDB  OUTROS RECURSOS              Recursos próprios   
11995       PSDB  OUTROS RECURSOS    Recursos de pessoas físicas   
4688         MDB  OUTROS RECURSOS    Recursos de pessoas físicas   
20303        PDT  OUTROS RECURSOS    Recursos de pessoas físicas   
6565        PODE  OUTROS RECURSOS    Recursos de pessoas físicas   
9697         MDB  OUTROS RECURSOS              Recursos próprios   
19342        PDT  OUTROS RECURSOS              Recursos próprios   
69           PSB  OUTROS RECURSOS    Recursos de pessoas físicas   
1010          PP  OUTROS RECURSOS    Recursos de pessoas físicas   

      DS_NATUREZA_RECEITA        DS_ESPECIE_RECEITA  \
19880           ESTIMÁVEL                  Estimado   
21721          FINANCEIRO  Transferência eletrônica   
11995          FINANCEIRO  Transferência eletrônica   
4688            ESTIMÁVEL                  Estimado   
20303           ESTIMÁVEL                  Estimado   
6565           FINANCEIRO  Transferência eletrônica   
9697           FINANCEIRO       Depósito em espécie   
19342          FINANCEIRO  Transferência eletrônica   
69              ESTIMÁVEL                  Estimado   
1010           FINANCEIRO  Transferência eletrônica   

      DS_ESFERA_PARTIDARIA_DOADOR    NM_MUNICIPIO_DOADOR  \
19880                      #NULO#                JACUÍPE   
21721                      #NULO#            OURO BRANCO   
11995                      #NULO#                 #NULO#   
4688                       #NULO#                 #NULO#   
20303                      #NULO#                 #NULO#   
6565                       #NULO#                 #NULO#   
9697                       #NULO#  PORTO REAL DO COLÉGIO   
19342                      #NULO#             

#### Manipulando os dados

##### Verificar valores Ausentes

In [ ]:
#Valores não-nulos por coluna
dados_receitas.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23060 entries, 0 to 23059
Data columns (total 18 columns):
 #   Column                       Non-Null Count  Dtype  
---  ------                       --------------  -----  
 0   CD_ELEICAO                   23060 non-null  int64  
 1   ST_TURNO                     23060 non-null  int64  
 2   TP_PRESTACAO_CONTAS          23060 non-null  object 
 3   NM_UE                        23060 non-null  object 
 4   DS_CARGO                     23060 non-null  object 
 5   SQ_CANDIDATO                 23060 non-null  int64  
 6   NR_CANDIDATO                 23060 non-null  int64  
 7   NM_CANDIDATO                 23060 non-null  object 
 8   NR_CPF_CANDIDATO             23060 non-null  int64  
 9   SG_PARTIDO                   23060 non-null  object 
 10  DS_FONTE_RECEITA             23060 non-null  object 
 11  DS_ORIGEM_RECEITA            23060 non-null  object 
 12  DS_NATUREZA_RECEITA          23060 non-null  object 
 13  DS_ESPECIE_RECEI

In [ ]:
#Número de valores ausentes para cada coluna
dados_receitas.isnull().sum()

CD_ELEICAO                     0
ST_TURNO                       0
TP_PRESTACAO_CONTAS            0
NM_UE                          0
DS_CARGO                       0
SQ_CANDIDATO                   0
NR_CANDIDATO                   0
NM_CANDIDATO                   0
NR_CPF_CANDIDATO               0
SG_PARTIDO                     0
DS_FONTE_RECEITA               0
DS_ORIGEM_RECEITA              0
DS_NATUREZA_RECEITA            0
DS_ESPECIE_RECEITA             0
DS_ESFERA_PARTIDARIA_DOADOR    0
NM_MUNICIPIO_DOADOR            0
DS_RECEITA                     0
VR_RECEITA                     0
dtype: int64

**Conclusão**: não há valores faltantes nessa tabela

##### Procurando inconsistèncias nos dados

In [ ]:
# verificando os valores únicos na tabela e se realmente so existe o 1º turno nela após o filtro
dados_receitas.nunique()

CD_ELEICAO                        1
ST_TURNO                          2
TP_PRESTACAO_CONTAS               4
NM_UE                           102
DS_CARGO                          2
SQ_CANDIDATO                   5231
NR_CANDIDATO                   1092
NM_CANDIDATO                   5197
NR_CPF_CANDIDATO               5231
SG_PARTIDO                       30
DS_FONTE_RECEITA                  3
DS_ORIGEM_RECEITA                 6
DS_NATUREZA_RECEITA               2
DS_ESPECIE_RECEITA                8
DS_ESFERA_PARTIDARIA_DOADOR       4
NM_MUNICIPIO_DOADOR             103
DS_RECEITA                     4436
VR_RECEITA                     2399
dtype: int64

In [ ]:
dados_receitas['DS_CARGO'].unique() # Verificando os cargos presentes na tabela

array(['Vereador', 'Prefeito'], dtype=object)

In [ ]:
dados_receitas['TP_PRESTACAO_CONTAS'].value_counts() # Verificando os tipo de prestação de conta na tabela

FINAL                       22556
PARCIAL                       413
RELATÓRIO FINANCEIRO           86
REGULARIZAÇÃO DA OMISSÃO        5
Name: TP_PRESTACAO_CONTAS, dtype: int64

In [ ]:
dados_receitas['NM_UE'].unique() # Verificando os municipios

array(['BOCA DA MATA', 'UNIÃO DOS PALMARES', 'PILAR', 'LAGOA DA CANOA',
       'PIRANHAS', 'ATALAIA', 'CAPELA', 'TAQUARANA', 'MAR VERMELHO',
       'MARECHAL DEODORO', 'LIMOEIRO DE ANADIA', 'ANADIA', 'ÁGUA BRANCA',
       'DELMIRO GOUVEIA', 'VIÇOSA', 'TRAIPU', 'BRANQUINHA', 'MACEIÓ',
       'PENEDO', 'CRAÍBAS', 'JACUÍPE', 'COITÉ DO NÓIA', 'JUNQUEIRO',
       "OLHO D'ÁGUA DAS FLORES", 'SÃO MIGUEL DOS CAMPOS', 'MAJOR ISIDORO',
       'RIO LARGO', 'SANTANA DO IPANEMA', 'ARAPIRACA', 'CORURIPE',
       'FEIRA GRANDE', 'PORTO DE PEDRAS', 'PORTO REAL DO COLÉGIO',
       'MURICI', 'MARAGOGI', 'BARRA DE SÃO MIGUEL', 'PAULO JACINTO',
       'NOVO LINO', 'CAMPO GRANDE', 'COLÔNIA LEOPOLDINA', 'MARIBONDO',
       'PIAÇABUÇU', 'IGREJA NOVA', 'QUEBRANGULO', 'SÃO JOSÉ DA LAJE',
       'SÃO JOSÉ DA TAPERA', 'CAMPO ALEGRE', 'MARAVILHA',
       'MATRIZ DE CAMARAGIBE', 'JAPARATINGA', 'COQUEIRO SECO',
       'TEOTÔNIO VILELA', 'SÃO LUÍS DO QUITUNDE', 'PALESTINA',
       'MINADOR DO NEGRÃO', "OLHO D'ÁGUA GR

In [ ]:
dados_receitas['SG_PARTIDO'].unique() # Verificando os partidos presentes na tabela

array(['PDT', 'PT', 'PSC', 'PV', 'SOLIDARIEDADE', 'PODE', 'REPUBLICANOS',
       'PP', 'MDB', 'PROS', 'PSD', 'PSB', 'PSDB', 'DEM', 'CIDADANIA',
       'PTB', 'REDE', 'PMN', 'PSOL', 'PL', 'PATRIOTA', 'DC', 'PSL', 'UP',
       'PRTB', 'AVANTE', 'PTC', 'PC do B', 'PCB', 'PSTU'], dtype=object)

In [ ]:
dados_receitas['NR_CPF_CANDIDATO'].unique() # 

array([6176245427,  861010485, 3749271461, ..., 5851334410, 2345253479,
       6893648499])

In [ ]:
dados_receitas['DS_FONTE_RECEITA'].unique() # Verificando os tipos de fonte de receita

array(['OUTROS RECURSOS', 'FUNDO ESPECIAL', 'FUNDO PARTIDARIO'],
      dtype=object)

In [ ]:
dados_receitas['DS_ORIGEM_RECEITA'].unique() # Verificando a origem

array(['Recursos de pessoas físicas', 'Recursos próprios',
       'Recursos de partido político', 'Recursos de outros candidatos',
       'Recursos de Financiamento Coletivo',
       'Recursos de origens não identificadas'], dtype=object)

In [ ]:
dados_receitas['DS_NATUREZA_RECEITA'].unique() # Verificando a natureza

array(['FINANCEIRO', 'ESTIMÁVEL'], dtype=object)

In [ ]:
dados_receitas['DS_ESPECIE_RECEITA'].value_counts()

Estimado                     10372
Transferência eletrônica      8858
Depósito em espécie           3521
Cheque                         269
Outros títulos de crédito       16
Em espécie                      14
Não informado                    7
Cartão de débito                 3
Name: DS_ESPECIE_RECEITA, dtype: int64

In [ ]:
dados_receitas['DS_ESFERA_PARTIDARIA_DOADOR'].unique() # 

array(['#NULO#', 'Federal (Estadual/Distrital)', 'Nacional', 'Municipal'],
      dtype=object)

In [ ]:
dados_receitas['NM_MUNICIPIO_DOADOR'].unique() # 

array(['#NULO#', 'ÁGUA BRANCA', 'CAPELA', 'DELMIRO GOUVEIA', 'VIÇOSA',
       'TRAIPU', 'BRANQUINHA', 'MACEIÓ', 'PENEDO', 'CRAÍBAS', 'JACUÍPE',
       'COITÉ DO NÓIA', 'TAQUARANA', 'PAULO JACINTO', 'LAGOA DA CANOA',
       'UNIÃO DOS PALMARES', 'PALESTINA', 'QUEBRANGULO',
       'PASSO DE CAMARAGIBE', 'SÃO SEBASTIÃO', 'MINADOR DO NEGRÃO',
       'MARECHAL DEODORO', 'BARRA DE SANTO ANTÔNIO', 'MESSIAS',
       'COLÔNIA LEOPOLDINA', 'MARAGOGI', 'PALMEIRA DOS ÍNDIOS',
       'CACIMBINHAS', 'NOVO LINO', 'SÃO JOSÉ DA TAPERA', 'PARICONHA',
       'PÃO DE AÇÚCAR', "OLHO D'ÁGUA DO CASADO", 'SANTANA DO IPANEMA',
       'IBATEGUARA', 'SÃO LUÍS DO QUITUNDE', 'IGREJA NOVA',
       "OLHO D'ÁGUA GRANDE", 'CAMPESTRE', 'BARRA DE SÃO MIGUEL',
       'JEQUIÁ DA PRAIA', 'SÃO BRÁS', 'ARAPIRACA',
       'PORTO REAL DO COLÉGIO', 'ANADIA', 'FLEXEIRAS', 'MATA GRANDE',
       'FELIZ DESERTO', 'PORTO CALVO', 'PIAÇABUÇU', 'LIMOEIRO DE ANADIA',
       'SATUBA', 'CAJUEIRO', 'FEIRA GRANDE', 'BATALHA', 'PILAR',
     

In [ ]:
dados_receitas['DS_RECEITA'].unique() # 

array(['#NULO#',
       'SERVIÇOS DE PANFLETAGEM E/OU ADESIVAÇÃO E/OU MOBILIZAÇÃO',
       'MOBILIZAÇÃO DE RUA', ...,
       'CESSAO VEICULO FIAT ARGO PLACA QPS2J81',
       'CESSÃO DE VEICULO FORD KA SE 1.0 HA C· PARA UTILIZAÇÃO EM CAMPANHA ELEITORAL 2020',
       'SANTINHOS-BURECO - SANDRINHO'], dtype=object)

In [ ]:
dados_receitas['VR_RECEITA'].unique() # Verificando o valor da receita

array([ 750.  ,  100.  , 1045.  , ...,  535.  , 1214.39,   28.2 ])

In [ ]:
# O código e a descrição da receita não serão nescessarios
dados_receitas = dados_receitas.drop(columns=['CD_ELEICAO', 'DS_RECEITA'])

In [ ]:
dados_receitas.columns.values

array(['ST_TURNO', 'TP_PRESTACAO_CONTAS', 'NM_UE', 'DS_CARGO',
       'SQ_CANDIDATO', 'NR_CANDIDATO', 'NM_CANDIDATO', 'NR_CPF_CANDIDATO',
       'SG_PARTIDO', 'DS_FONTE_RECEITA', 'DS_ORIGEM_RECEITA',
       'DS_NATUREZA_RECEITA', 'DS_ESPECIE_RECEITA',
       'DS_ESFERA_PARTIDARIA_DOADOR', 'NM_MUNICIPIO_DOADOR', 'VR_RECEITA'],
      dtype=object)

### Tabela 4 - Despesas Contratadas

#### Descrição dos principais atributos

**Pricipais atributos do dataset**: 

* **(int)** - CD_ELEICAO  - Código da eleição

* **(int)** - ST_TURNO - O indicativo se prestador de contas teve prestação para 2º turno

* **(int)** - TP_PRESTACAO_CONTAS - Tipo de entrega da prestação de contas. Pode assumir os valores: 0 - Final, 1 - Relatório Financeiro e 2 - Parcial.

* * Tipo 0 - Final: é o tipo de entrega final da prestação de contas, onde serão gerados os relatórios de análise, exame, diligência e conclusivo. 

* * Tipo 1 - Relatório Financeiro: prazo de 72h, após a arrecadação, em que o prestador de contas deve informar à Justiça Eleitoral as doações recebidas. 

* * Tipo 2 - Parcial: prazo no qual os prestadores de contas são obrigados a enviar à Justiça Eleitoral as prestações de contas completas para avaliação prévia, antes da análise da final. 

* **(str)** - SQ_PRESTADOR_CONTAS - Número sequencial do prestador de contas, gerado internamento pelos sistemas eleitorais para cada eleição. 

* **(str)** - NM_UE - Nome da Unidade Eleitoral do candidato prestador de 
contas.

* **(str)** - DS_CARGO - Cargo concorrido na eleição pelo candidato prestador de contas.

* **(str)** - SQ_CANDIDATO - Número sequencial do candidato, gerado internamente pelos sistemas eleitorais para cada eleição.

* **(str)** - NR_CANDIDATO - Número do candidato prestador de contas na eleição

* **(str)** - NM_CANDIDATO - Nome completo do candidato prestador de contas. 

* **(str)** - NR_CPF_CANDIDATO - Número do CPF do candidato prestador de contas

* **(str)** - SG_PARTIDO - Sigla do partido do candidato prestador de contas. 

* **(str)** - DS_TIPO_FORNECEDOR - Tipo de natureza jurídica do fornecedor, informado pelo candidato prestador de contas em relação à despesa.

* **(str)** - NM_FORNECEDOR - Nome, declarado à Justiça Eleitoral, do fornecedor de bens e/ou serviços da despesa informada pelo candidato 
prestador de contas.

* **(str)** - DS_ORIGEM_DESPESA - Descrição do tipo de origem da despesa

* **(str)** - SQ_DESPESA - Sequencial de identificação do registro da despesa

* **(str)** - DS_DESPESA - Descrição da aplicabilidade da despesa contratada, informada pelo prestador de contas.

* **(str)** - VR_DESPESA_CONTRATADA - Valor da despesa em Reais (R$)

**Quantidade de linhas: 9301**

*descrições tirados do pdf que vem junto da tabela*

#### Criando a tabela

In [ ]:
#Tabela com dados sobre as despesas contratadas pelos candidatos
colunasT3 = ['CD_ELEICAO', 'ST_TURNO', 'TP_PRESTACAO_CONTAS', 'SQ_PRESTADOR_CONTAS', 'NM_UE', 'DS_CARGO', 'SQ_CANDIDATO', 'NR_CANDIDATO',
             'NM_CANDIDATO','NR_CPF_CANDIDATO', 'SG_PARTIDO', 'NR_CNPJ_PRESTADOR_CONTA', 'DS_TIPO_FORNECEDOR', 'NM_FORNECEDOR', 'DS_ORIGEM_DESPESA',
             'SQ_DESPESA', 'DS_DESPESA', 'VR_DESPESA_CONTRATADA']
dados_despesas_contratadas = pd.read_csv('/content/drive/My Drive/Visualização Computacional/despesas_contratadas_candidatos_2020_AL.csv', sep=";",
                                         encoding='latin-1', usecols=colunasT3)

In [ ]:
# Filtrando com base no código do 1º turno da eleição ordinaria e se o cadidato esta apto a ir as urnas
dados_despesas_contratadas = dados_despesas_contratadas.loc[(dados_despesas_contratadas['CD_ELEICAO'] == 426) ].reset_index(drop=True)

In [ ]:
# filtro apanas o relatorio final da despesas
dados_despesas_contratadas = dados_despesas_contratadas.loc[(dados_despesas_contratadas['TP_PRESTACAO_CONTAS'] == 'Final') ].reset_index(drop=True)

In [ ]:
dados_despesas_contratadas['VR_DESPESA_CONTRATADA'] = dados_despesas_contratadas['VR_DESPESA_CONTRATADA'].str.replace(',', '.') # troca o , por ponto
dados_despesas_contratadas['VR_DESPESA_CONTRATADA'] = dados_despesas_contratadas['VR_DESPESA_CONTRATADA'].astype(float) # Convertendo para float
dados_despesas_contratadas['VR_DESPESA_CONTRATADA'].unique()

array([   7.5 ,   50.  ,  100.  , ...,   35.98, 1000.8 ,  299.8 ])

#### Visualizando os Dados

In [ ]:
dados_despesas_contratadas.head(10)

CD_ELEICAO  ST_TURNO TP_PRESTACAO_CONTAS  SQ_PRESTADOR_CONTAS  \
0         426         1               Final           1843810734   
1         426         1               Final           1843182235   
2         426         1               Final           1844842585   
3         426         1               Final           1841599022   
4         426         1               Final           1846988076   
5         426         1               Final           1843717926   
6         426         1               Final           1841599022   
7         426         1               Final           1841599022   
8         426         1               Final           1841599022   
9         426         1               Final           1841599022   

                   NM_UE  NR_CNPJ_PRESTADOR_CONTA  DS_CARGO  SQ_CANDIDATO  \
0        DELMIRO GOUVEIA           38769308000179  Prefeito   20000830521   
1                 VIÇOSA           38669055000161  Vereador   20000757944   
2     OLHO D'ÁGUA GRANDE           38858030000106  Vereador   20000938207   
3              TAQUARANA           38851232000126  Prefeito   20000753347   
4             PARIPUEIRA           38964489000194  Vereador   20001060946   
5  SÃO MIGUEL DOS CAMPOS           38764323000124  Prefeito   20000816470   
6              TAQUARANA           38851232000126  Prefeito   20000753347   
7              TAQUARANA           38851232000126  Prefeito   20000753347   
8              TAQUARANA           38851232000126  Prefeito   20000753347   
9              TAQUARANA           38851232000126  Prefeito   20000753347   

   NR_CANDIDATO                   NM_CANDIDATO  NR_CPF_CANDIDATO SG_PARTIDO  \
0            15        ELIZIANE FERREIRA COSTA       64805395400        MDB   
1         15123         FLAVIO ALVES DE FRANÇA        5542507484        MDB   
2         55000  KLEBERTON SANTOS DE ALCANTARA        7083590435        PSD   
3            12      RAFAEL PEREIRA DE ALMEIDA       92554636400        PDT   
4         25999         EDIANE SANTOS DA SILVA        4620716421        DEM   
5            25     PEDRO RICARDO ALVES JATOBÁ       45385670430        DEM   
6            12      RAFAEL PEREIRA DE ALMEIDA       92554636400        PDT   
7            12      RAFAEL PEREIRA DE ALMEIDA       92554636400        PDT   
8            12      RAFAEL PEREIRA DE ALMEIDA       92554636400        PDT   
9            12      RAFAEL PEREIRA DE ALMEIDA       92554636400        PDT   

  DS_TIPO_FORNECEDOR                                 NM_FORNECEDOR  \
0    Pessoa Jurídica                          POSTO ALINE LTDA EPP   
1    Pessoa Jurídica                     I9 SOLUÇÕES GRÁFICAS LTDA   
2      Pessoa Física                     EDICLEI ALMEIDA DA SILVA    
3    Pessoa Jurídica  JOAO LUCAS DO NASCIMENTO ALMEIDA 10987736400   
4    Pessoa Jurídica                    CW MONTEIRO DE CARVALHO ME   
5      Pessoa Física                              EDILENE DE SOUZA   
6    Pessoa Jurídica  JOAO LUCAS DO NASCIMENTO ALMEIDA 10987736400   
7    Pessoa Jurídica  JOAO LUCAS DO NASCIMENTO ALMEIDA 10987736400   
8    Pessoa Jurídica  JOAO LUCAS DO NASCIMENTO ALMEIDA 10987736400   
9    Pessoa Jurídica  JOAO LUCAS DO NASCIMENTO ALMEIDA 10987736400   

                               DS_ORIGEM_DESPESA  SQ_DESPESA  \
0                                           Água    39993554   
1            Publicidade por materiais impressos    37780866   
2        Produção de jingles, vinhetas e slogans    36046286   
3            Publicidade por materiais impressos    38677841   
4            Publicidade por materiais impressos    40806000   
5  Atividades de militância e mobilização de rua    41039082   
6            Publicidade por materiais impressos    38677841   
7            Publicidade por materiais impressos    38677841   
8            Publicidade por materiais impressos    38677841   
9            Publicidade por materiais impressos    38677841   

                   DS_DESPESA  VR_DESPESA_CONTRATADA  
0  CO

In [ ]:
dados_despesas_contratadas.sample(10)

CD_ELEICAO  ST_TURNO TP_PRESTACAO_CONTAS  SQ_PRESTADOR_CONTAS  \
11179         426         1               Final           1849841424   
6812          426         1               Final           1849831126   
23384         426         1               Final           1845700104   
10182         426         1               Final           1846950230   
22596         426         1               Final           1845042142   
33005         426         1               Final           1845741047   
51334         426         1               Final           1843147240   
23304         426         1               Final           1843138198   
30764         426         1               Final           1843204197   
49217         426         1               Final           1834911822   

                      NM_UE  NR_CNPJ_PRESTADOR_CONTA  DS_CARGO  SQ_CANDIDATO  \
11179    UNIÃO DOS PALMARES           39093657000186  Prefeito   20001190088   
6812     UNIÃO DOS PALMARES           39101945000135  Vereador   20001174070   
23384            JARAMATAIA           38871290000111  Prefeito   20001004142   
10182                 IGACI           39181304000138  Vereador   20001026224   
22596               ATALAIA           38832920000149  Vereador   20000957823   
33005  MATRIZ DE CAMARAGIBE           38912982000160  Prefeito   20001001830   
51334   PALMEIRA DOS ÍNDIOS           38693901000189  Vereador   20000804116   
23304         SÃO SEBASTIÃO           38697566000197  Prefeito   20000800753   
30764                MACEIÓ           38718353000102  Vereador   20000775858   
49217      MARECHAL DEODORO           38576218000161  Prefeito   20000688280   

       NR_CANDIDATO                                   NM_CANDIDATO  \
11179            14             JOSÉ ALFREDO SOARES LINS WANDERLEY   
6812          23023               ANTONIO ALEXANDRE DE LIMA CASTRO   
23384            40                       JEFFERSON TORRES BARRETO   
10182         14100                       SOLANIO CALIXTO DA ROCHA   
22596         15888                      MARCOS ANDRE MACENA ALVES   
33005            20  OCTAVIO HENRIQUE DA SILVA NASCIMENTO BOLEVARD   
51334         13345                       JOELMA KELLMA DOS SANTOS   
23304            15                          LUIZ ANTONIO DA SILVA   
30764         40190                    FÁBIO MICHEY COSTA DA SILVA   
49217            15                 CLAUDIO ROBERTO AYRES DA COSTA   

       NR_CPF_CANDIDATO SG_PARTIDO DS_TIPO_FORNECEDOR  \
11179       64707199453        PTB    Pessoa Jurídica   
6812         4219197443  CIDADANIA    Pessoa Jurídica   
23384       92467679420        PSB    Pessoa Jurídica   
10182        8307206855        PTB    Pessoa Jurídica   
22596         797864482        MDB    Pessoa Jurídica   
33005       10293792461        PSC    Pessoa Jurídica   
51334        7942444406         PT    Pessoa Jurídica   
23304       24071668415        MDB    Pessoa Jurídica   
30764        3861274418        PSB    Pessoa Jurídica   
49217        4688098480        MDB    Pessoa Jurídica   

                                           NM_FORNECEDOR  \
11179                                  ANDERSON FERREIRA   
6812            GRÁFICA E EDITORA MASCARENHAS EIRELI EPP   
23384             QUEIROZ E FREITAS ADVOGADOS ASSOCIADOS   
10182                      GRAFICA LIDDER E EDITORA LTDA   
22596                         JOSE NOGUEIRA MENDES FILHO   
33005  GRUPO DE MARKETING SÃO JUDAS TADEU LTDA - TDL ...   
51334                   DENISSON RODRIGO COSTA DA SILVA    
23304                      SANTANA   SACRAMENTO LTDA EPP   
30764                                      AUTO POSTO R2   
49217      GRAFMARQUES INDUSTRIA EDITORA E SERVIÇOS LTDA   

                                      DS_ORIGEM_DESPESA  SQ_DESPESA  \
11179  Doações financeiras a outros candidatos/partidos    37717667   
6812                Publicidade por materiais impressos    39576010   
23384                             Serviços advocatícios    3

#### Manipulando os dados

##### Verificar valores Ausentes

In [ ]:
#Valores não-nulos por coluna
dados_despesas_contratadas.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 65873 entries, 0 to 65872
Data columns (total 18 columns):
 #   Column                   Non-Null Count  Dtype  
---  ------                   --------------  -----  
 0   CD_ELEICAO               65873 non-null  int64  
 1   ST_TURNO                 65873 non-null  int64  
 2   TP_PRESTACAO_CONTAS      65873 non-null  object 
 3   SQ_PRESTADOR_CONTAS      65873 non-null  int64  
 4   NM_UE                    65873 non-null  object 
 5   NR_CNPJ_PRESTADOR_CONTA  65873 non-null  int64  
 6   DS_CARGO                 65873 non-null  object 
 7   SQ_CANDIDATO             65873 non-null  int64  
 8   NR_CANDIDATO             65873 non-null  int64  
 9   NM_CANDIDATO             65873 non-null  object 
 10  NR_CPF_CANDIDATO         65873 non-null  int64  
 11  SG_PARTIDO               65873 non-null  object 
 12  DS_TIPO_FORNECEDOR       65873 non-null  object 
 13  NM_FORNECEDOR            65873 non-null  object 
 14  DS_ORIGEM_DESPESA     

In [ ]:
#Número de valores ausentes para cada coluna
dados_despesas_contratadas.isnull().sum()

CD_ELEICAO                 0
ST_TURNO                   0
TP_PRESTACAO_CONTAS        0
SQ_PRESTADOR_CONTAS        0
NM_UE                      0
NR_CNPJ_PRESTADOR_CONTA    0
DS_CARGO                   0
SQ_CANDIDATO               0
NR_CANDIDATO               0
NM_CANDIDATO               0
NR_CPF_CANDIDATO           0
SG_PARTIDO                 0
DS_TIPO_FORNECEDOR         0
NM_FORNECEDOR              0
DS_ORIGEM_DESPESA          0
SQ_DESPESA                 0
DS_DESPESA                 0
VR_DESPESA_CONTRATADA      0
dtype: int64

**Conclusão**: não há valores faltantes nessa tabela

##### Procurando inconsistèncias nos dados

In [ ]:
# verificando se realmente so existe o 1º turno na tabela
#
dados_despesas_contratadas.nunique()

CD_ELEICAO                     1
ST_TURNO                       2
TP_PRESTACAO_CONTAS            1
SQ_PRESTADOR_CONTAS         4276
NM_UE                        102
NR_CNPJ_PRESTADOR_CONTA     4276
DS_CARGO                       2
SQ_CANDIDATO                4276
NR_CANDIDATO                 900
NM_CANDIDATO                4257
NR_CPF_CANDIDATO            4276
SG_PARTIDO                    29
DS_TIPO_FORNECEDOR             2
NM_FORNECEDOR              23815
DS_ORIGEM_DESPESA             38
SQ_DESPESA                 48215
DS_DESPESA                 24633
VR_DESPESA_CONTRATADA       5764
dtype: int64

In [ ]:
dados_despesas_contratadas['ST_TURNO'].unique() # Se o candidato foi pro 2 turno ou não

array([1, 2])

In [ ]:
dados_despesas_contratadas['TP_PRESTACAO_CONTAS'].unique() # Tipo de prestação de conta

array(['Final'], dtype=object)

In [ ]:
dados_despesas_contratadas['DS_CARGO'].unique() # verificando os cargos presentes

array(['Prefeito', 'Vereador'], dtype=object)

In [ ]:
dados_despesas_contratadas['NM_UE'].unique() # verificando os municipios

array(['DELMIRO GOUVEIA', 'VIÇOSA', "OLHO D'ÁGUA GRANDE", 'TAQUARANA',
       'PARIPUEIRA', 'SÃO MIGUEL DOS CAMPOS', 'SÃO JOSÉ DA LAJE',
       'MACEIÓ', 'PENEDO', 'PASSO DE CAMARAGIBE', 'GIRAU DO PONCIANO',
       'TEOTÔNIO VILELA', 'SÃO SEBASTIÃO', 'OLIVENÇA', 'MARECHAL DEODORO',
       'ARAPIRACA', 'MARAGOGI', 'FEIRA GRANDE', 'PALMEIRA DOS ÍNDIOS',
       'SÃO JOSÉ DA TAPERA', 'CAMPO ALEGRE', 'JUNQUEIRO', 'CAPELA',
       'RIO LARGO', 'MATRIZ DE CAMARAGIBE', 'SÃO LUÍS DO QUITUNDE',
       'PIAÇABUÇU', "OLHO D'ÁGUA DAS FLORES", 'SENADOR RUI PALMEIRA',
       'FELIZ DESERTO', 'COLÔNIA LEOPOLDINA', 'LIMOEIRO DE ANADIA',
       'SATUBA', 'MESSIAS', 'LAGOA DA CANOA', 'IBATEGUARA',
       'UNIÃO DOS PALMARES', 'CORURIPE', 'ROTEIRO', 'BARRA DE SÃO MIGUEL',
       'MINADOR DO NEGRÃO', 'IGACI', 'PILAR', 'SÃO BRÁS', 'MARIBONDO',
       'ESTRELA DE ALAGOAS', 'INHAPI', 'PORTO CALVO', 'IGREJA NOVA',
       'FLEXEIRAS', 'CHÃ PRETA', 'PÃO DE AÇÚCAR', 'JAPARATINGA',
       'CAMPESTRE', 'MONTEIRÓPOL

In [ ]:
dados_despesas_contratadas['NR_CPF_CANDIDATO'].unique() # existem cpfs com menos de 11 digitos então não é bom criterio para agrupar

array([64805395400,  5542507484,  7083590435, ..., 67964290444,
       59156562420, 15394751404])

In [ ]:
dados_despesas_contratadas['NR_CNPJ_PRESTADOR_CONTA'].unique() # cnpj

array([38769308000179, 38669055000161, 38858030000106, ...,
       39193351000100, 39092774000125, 39107134000141])

In [ ]:
dados_despesas_contratadas['NR_CANDIDATO'].unique() # numero dos candidatos

array([   15, 15123, 55000,    12, 25999,    25, 11222, 45000,    11,
       45500, 40222, 13300, 11999, 14444, 90123, 45123, 11555, 28100,
       22111, 18777, 11111,    14, 19888, 40190,    10,    40, 11456,
          20, 15999,    22, 40888,    45, 15007, 40444, 45678, 11333,
       11888, 15444, 12444, 77777, 25122, 12777, 23000, 15567, 14555,
          55, 17017, 15789, 14777,    77,    51, 13000,    23,    90,
       14111, 19000, 25111, 65555, 13444,    18, 55400, 15555, 10666,
       17000, 40456, 11000, 40321, 45222, 15111,    33, 12012, 15666,
       45333, 15000, 18000, 13222, 15116, 11234, 15777, 10110, 43222,
       33333, 45999, 15001, 90000, 14123, 11789, 15888, 15151, 40240,
       15678, 40666, 13113, 10111, 40000, 12678, 65123, 15234, 15100,
       10000, 20888, 55500, 13999, 40111, 20133, 15498, 14999, 20200,
       40123, 55222, 33000, 90111, 45613, 11777, 43124, 18618, 14144,
       11300, 51111, 15321, 90200,    13, 55666, 51666, 10456, 25678,
       45789, 45555,

In [ ]:
# Como não deveria existir números de candidatos iguais em uma UE poderia ser um criterio para agrupar os dados além do SQ do candidato
dados_despesas_contratadas[['NM_UE', 'NR_CANDIDATO']].value_counts()

NM_UE                  NR_CANDIDATO
MACEIÓ                 40              4334
MARECHAL DEODORO       15              1219
ARAPIRACA              10               884
RIO LARGO              40               836
SÃO MIGUEL DOS CAMPOS  25               617
                                       ... 
SÃO JOSÉ DA TAPERA     25775              1
BELÉM                  15777              1
SÃO JOSÉ DA TAPERA     45222              1
OLIVENÇA               10789              1
MACEIÓ                 17003              1
Length: 4271, dtype: int64

In [ ]:
# Verificando se realmente não há candidatos na mesma cidade com o mesmo número
a =dados_despesas_contratadas[['NM_UE', 'NR_CANDIDATO','NM_CANDIDATO']].value_counts().reset_index() # add o nome do candidato para ter certeza /
                                                                                                      # que nomes diferentes não sejam agrupados
a

NM_UE  NR_CANDIDATO                    NM_CANDIDATO  \
0                    MACEIÓ            40    JOÃO HENRIQUE HOLANDA CALDAS   
1          MARECHAL DEODORO            15  CLAUDIO ROBERTO AYRES DA COSTA   
2                 ARAPIRACA            10       FABIANA CAVALCANTE PESSOA   
3                 RIO LARGO            40   PEDRO VICTOR DE ARAUJO JUNIOR   
4     SÃO MIGUEL DOS CAMPOS            25      PEDRO RICARDO ALVES JATOBÁ   
...                     ...           ...                             ...   
4271     ESTRELA DE ALAGOAS         11999           JOÃO BATISTA DA SILVA   
4272     SÃO JOSÉ DA TAPERA         45222         JOSÉ AGNALDO DOS SANTOS   
4273     SÃO JOSÉ DA TAPERA         45444        IRANILDO SANTOS DA SILVA   
4274     SÃO JOSÉ DA TAPERA         45777       VALERIA RODRIGUES FEITOSA   
4275               MARAGOGI         13567           NORMA MARIA DE CAMPOS   

         0  
0     4334  
1     1219  
2      884  
3      836  
4      617  
...    ...  
4271     1  
4272     1  
4273     1  
4274     1  
4275     1  

[4276 rows x 4 columns]

In [ ]:
a[['NM_UE', 'NR_CANDIDATO']].value_counts() # existem mais de um candidato na mesma cidade com o mesmo número

NM_UE             NR_CANDIDATO
PORTO CALVO       55              3
MARECHAL DEODORO  12000           2
PARICONHA         15              2
MATA GRANDE       14567           2
ANADIA            11              1
                                 ..
JEQUIÁ DA PRAIA   10000           1
                  10111           1
                  10123           1
                  10333           1
ÁGUA BRANCA       90999           1
Length: 4271, dtype: int64

In [ ]:
# Há alguns candidatos que renunciaram mas que tiveram gastos e foram substituidos por novos candidatos que usam o msm número
dados_despesas_contratadas[(dados_despesas_contratadas['NR_CANDIDATO'] == 55) & (dados_despesas_contratadas['NM_UE'] == 'PORTO CALVO')]

CD_ELEICAO  ST_TURNO TP_PRESTACAO_CONTAS  SQ_PRESTADOR_CONTAS  \
3634          426         1               Final           1931105935   
4285          426         1               Final           1843769035   
5321          426         1               Final           1883957508   
5322          426         1               Final           1883957508   
5323          426         1               Final           1883957508   
6767          426         1               Final           1843769035   
8763          426         1               Final           1883957508   
11712         426         1               Final           1931105935   
11713         426         1               Final           1931105935   
11714         426         1               Final           1931105935   
11715         426         1               Final           1931105935   
14074         426         1               Final           1843769035   
14075         426         1               Final           1843769035   
15633         426         1               Final           1883957508   
16401         426         1               Final           1843769035   
21291         426         1               Final           1843769035   
25393         426         1               Final           1843769035   
27334         426         1               Final           1931105935   
28704         426         1               Final           1843769035   
35666         426         1               Final           1883957508   
35667         426         1               Final           1883957508   
35668         426         1               Final           1883957508   
35669         426         1               Final           1883957508   
35670         426         1               Final           1883957508   
35671         426         1               Final           1883957508   
35672         426         1               Final           1883957508   
35673         426         1               Final           1883957508   
35674         426         1               Final           1883957508   
35675         426         1               Final           1883957508   
37630         426         1               Final           1843769035   
38927         426         1               Final           1883957508   
39423         426         1               Final           1883957508   
40728         426         1               Final           1931105935   
40871         426         1               Final           1931105935   
40872         426         1               Final           1931105935   
40873         426         1               Final           1931105935   
40874         426         1               Final           1931105935   
40875         426         1               Final           1931105935   
40876         426         1               Final           1931105935   
40877         426         1               Final           1931105935   
40878         426         1               Final           1931105935   
45195         426         1               Final           1931105935   
45867         426         1               Final           1883957508   
50377         426         1               Final           1883957508   
53525         426         1               Final           1843769035   
53758         426         1               Final           1883957508   
55742         426         1               Final           1883957508   
56752         426         1               Final           1883957508   
56771         426         1               Final           1931105935   
59366         426         1               Final           1931105935   
59476         426         1               Final           1883957508   
61113         426         1               Final           1843769035   
64797         426         1               Final           1931105935   
65058         426         1               Final           1883957508   

             NM_UE  NR_CNPJ_PRESTADOR_CONTA  D

In [ ]:
dados_despesas_contratadas['SG_PARTIDO'].unique() # Partidos

array(['MDB', 'PSD', 'PDT', 'DEM', 'PP', 'PSDB', 'PSB', 'PT', 'PTB',
       'PROS', 'PRTB', 'PL', 'REDE', 'PODE', 'REPUBLICANOS', 'PSC',
       'SOLIDARIEDADE', 'CIDADANIA', 'PSL', 'PATRIOTA', 'PC do B', 'PMN',
       'PV', 'PSOL', 'AVANTE', 'PTC', 'UP', 'PCB', 'DC'], dtype=object)

In [ ]:
dados_despesas_contratadas['DS_TIPO_FORNECEDOR'].unique() # fornecedor

array(['Pessoa Jurídica', 'Pessoa Física'], dtype=object)

In [ ]:
dados_despesas_contratadas['DS_ORIGEM_DESPESA'].unique() # origem da despesa

array(['Água', 'Publicidade por materiais impressos',
       'Produção de jingles, vinhetas e slogans',
       'Atividades de militância e mobilização de rua',
       'Serviços prestados por terceiros', 'Diversas a especificar',
       'Despesas com pessoal', 'Serviços advocatícios',
       'Despesas com transporte ou deslocamento',
       'Eventos de promoção da candidatura', 'Serviços contábeis',
       'Alimentação', 'Taxa de Administração de Financiamento Coletivo',
       'Combustíveis e lubrificantes', 'Publicidade por adesivos',
       'Publicidade por carros de som', 'Cessão ou locação de veículos',
       'Locação/cessão de bens imóveis',
       'Despesa com Impulsionamento de Conteúdos',
       'Encargos financeiros, taxas bancárias e/ou op. cartão de crédito',
       'Doações financeiras a outros candidatos/partidos',
       'Serviços próprios prestados por terceiros',
       'Materiais de expediente', 'Comícios',
       'Produção de programas de rádio, televisão ou vídeo',


In [ ]:
dados_despesas_contratadas['DS_ORIGEM_DESPESA'].value_counts() # Verificando quais despesas mais aparecem

Publicidade por materiais impressos                                 15579
Encargos financeiros, taxas bancárias e/ou op. cartão de crédito     9947
Atividades de militância e mobilização de rua                        9757
Publicidade por adesivos                                             6072
Despesas com pessoal                                                 5844
Serviços prestados por terceiros                                     5198
Combustíveis e lubrificantes                                         3167
Produção de jingles, vinhetas e slogans                              1927
Diversas a especificar                                               1497
Serviços contábeis                                                   1170
Serviços advocatícios                                                 962
Cessão ou locação de veículos                                         773
Alimentação                                                           661
Despesa com Impulsionamento de Conteúd

In [ ]:
dados_despesas_contratadas['DS_DESPESA'].unique() # descrição da receita

array(['COMPRA DE AGUA - CAMINHADA', 'BOTTONS', 'PRODUÇAO DE UM JINGLE ',
       ..., ' ADESIVOS IMPRESSAO DIGITAL 30X10CM',
       'SANTINHO.DRAGEMOL A 10.000.6X9CIN· 4X0',
       'COMPOSIÇÃO DE JINGLE ELEITORAL '], dtype=object)

In [ ]:
dados_despesas_contratadas['VR_DESPESA_CONTRATADA'].unique() # está em string

array([   7.5 ,   50.  ,  100.  , ...,   35.98, 1000.8 ,  299.8 ])

In [ ]:
# O código e a descrição da despesa não será nescessarios
dados_despesas_contratadas = dados_despesas_contratadas.drop(columns=['CD_ELEICAO', 'DS_DESPESA'])

In [ ]:
dados_despesas_contratadas.columns.values

array(['ST_TURNO', 'TP_PRESTACAO_CONTAS', 'SQ_PRESTADOR_CONTAS', 'NM_UE',
       'NR_CNPJ_PRESTADOR_CONTA', 'DS_CARGO', 'SQ_CANDIDATO',
       'NR_CANDIDATO', 'NM_CANDIDATO', 'NR_CPF_CANDIDATO', 'SG_PARTIDO',
       'DS_TIPO_FORNECEDOR', 'NM_FORNECEDOR', 'DS_ORIGEM_DESPESA',
       'SQ_DESPESA', 'VR_DESPESA_CONTRATADA'], dtype=object)

##### Verficar o número total de municipios presentes

In [ ]:
#Calculando o número de municipios e o numero de candidatos por municipio
dados_despesas_contratadas[['NM_UE']].value_counts()

NM_UE                
MACEIÓ                   14370
ARAPIRACA                 4089
SÃO MIGUEL DOS CAMPOS     2339
MARECHAL DEODORO          2153
PENEDO                    2014
                         ...  
CACIMBINHAS                144
PAULO JACINTO              139
BELÉM                      128
PORTO DE PEDRAS             99
PINDOBA                     77
Length: 102, dtype: int64

Conclusão: 
* Há 102 municipios quantificados, ou seja, todos os municipios do estado.
* 



#### Outros filtros

In [ ]:
# Sem transferencia entre candidatos
dados_despesas_contratadas1 = dados_despesas_contratadas.loc[(dados_despesas_contratadas['DS_ORIGEM_DESPESA'] ==
                                                             'Doações financeiras a outros candidatos/partidos') ].reset_index(drop=True)

### Tabela 5 - Detalhes da Votação por Municipio

#### Atributos da tabela

**Pricipais atributos do dataset**: 

*   NR_TURNO - Número do turno da eleição
* CD_ELEICAO - 426 indica as eleções municipais ordinarias no 1º turno
*   NM_MUNICIPIO - Nome do município onde ocorreu a eleição
*   NR_ZONA - Número da Zona onde ocorreu a eleição
*   DS_CARGO - Descrição do cargo do candidato
*   QT_APTOS_TOT -Quantidade de eleitores aptos nas seções totalizadas
*   QT_COMPARECIMENTO - Quantidade de eleitores que compareceram às 
eleições naquele município e zona, naquele cargo
*   QT_ABSTENCOES - Quantidade de eleitores que não compareceram às 
eleições naquele município e zona
*   ST_VOTO_EM_TRANSITO - Status que indica se o quantitativo de votos se refere a voto em trânsito
*   QT_VOTOS_NOMINAIS - Quantidade de votos nominais totalizados naquele 
município e zona
* QT_VOTOS_BRANCOS - Quantidade de votos brancos totalizados naquele 
município e zona
* QT_VOTOS_NULOS - Quantidade de votos nulos totalizados naquele 
município e zona
* QT_VOTOS_LEGENDA - Quantidade de votos em legenda totalizados naquele 
município e zona
* QT_VOTOS_ANULADOS - Quantidade de votos anulados e apurados como 
válidos naquele município e zona
* QT_VOTOS_NULO_TECNICO - Quantidade de votos nulos técnicos
* QT_VOTOS_ANULADO_SUB_JUDICE - Quantidade de votos anulados sub judice (indeferido com recurso)
* QT_VOTOS_SEM_CAND_P_VOTAR - Quantidade de votos sem candidatos para votar


-- Descrições dos atributos tiradas do arquivo read-me da tabela

**Quantidade de linhas** = 220

**Quantidade de Municipios** = 102 

**Problemas encontrados**:  

#### Lendo a Tabela

In [ ]:
colunas = ['NR_TURNO','CD_ELEICAO', 'NM_MUNICIPIO', 'NR_ZONA', 'DS_CARGO', 'QT_APTOS_TOT', 'QT_COMPARECIMENTO','QT_ABSTENCOES', 'ST_VOTO_EM_TRANSITO', 'QT_VOTOS_NOMINAIS',
           'QT_VOTOS_BRANCOS', 'QT_VOTOS_NULOS', 'QT_VOTOS_LEGENDA', 'QT_VOTOS_ANULADOS', 'QT_VOTOS_NULO_TECNICO',  'QT_VOTOS_ANULADO_SUB_JUDICE', 'QT_VOTOS_SEM_CAND_P_VOTAR']
dados_detalhe_votacao = pd.read_csv('/content/drive/My Drive/Visualização Computacional/detalhe_votacao_munzona_2020_AL.csv', sep=";", encoding='latin-1', usecols=colunas)
dados_detalhe_votacao
# geopandas comparecimento ou a tabela cpm as seções

NR_TURNO  CD_ELEICAO NM_MUNICIPIO  NR_ZONA  DS_CARGO  QT_APTOS_TOT  \
0           1         426   PARIPUEIRA       17  Prefeito         10382   
1           1         426   PARIPUEIRA       17  Vereador         10382   
2           1         426  ÁGUA BRANCA       39  Prefeito         15296   
3           1         426  ÁGUA BRANCA       39  Vereador         15296   
4           1         426    PARICONHA       39  Prefeito          8736   
..        ...         ...          ...      ...       ...           ...   
215         2         427       MACEIÓ        1  Prefeito        104125   
216         2         427       MACEIÓ        2  Prefeito        152192   
217         2         427       MACEIÓ        3  Prefeito        119805   
218         2         427       MACEIÓ       33  Prefeito         92475   
219         2         427       MACEIÓ       54  Prefeito        123791   

     QT_COMPARECIMENTO  QT_ABSTENCOES ST_VOTO_EM_TRANSITO  QT_VOTOS_NOMINAIS  \
0                 8677           1705                   N               8162   
1                 8677           1705                   N               7862   
2                11597           3699                   N              11012   
3                11597           3699                   N              10379   
4                 7046           1690                   N               6690   
..                 ...            ...                 ...                ...   
215              75740          28385                   N              66707   
216             108949          43243                   N              96799   
217              90293          29512                   N              80482   
218              65785          26690                   N              57831   
219              86882          36909                   N              77032   

     QT_VOTOS_BRANCOS  QT_VOTOS_NULOS  QT_VOTOS_LEGENDA  QT_VOTOS_ANULADOS  \
0                 150             365                 0                  0   
1                 117             260               438                  0   
2                  96             489                 0                  0   
3                 103             575               540                  0   
4                  56             300                 0                  0   
..                ...             ...               ...                ...   
215              2308            6725                 0                  0   
216              3135            9015                 0                  0   
217              2418            7393                 0                  0   
218              2234            5720                 0                  0   
219              2611            7239                 0                  0   

     QT_VOTOS_NULO_TECNICO  QT_VOTOS_ANULADO_SUB_JUDICE  \
0                        0                            0   
1                        0                            0   
2                        0                            0   
3                        0                            0   
4                        0                            0   
..                     ...                          ...   
215                      0                            0   
216                      0                            0   
217                      0                            0   
218                      0                            0   
219                      0                            0   

     QT_VOTOS_SEM_CAND_P_VOTAR  
0                            0  
1                            0  
2                            0  
3                            0  
4                            0  
..                         ...  
215                          0  
216                          0  
217                          0  
218                          0  
219                          0  

[220 rows x 17 columns]

In [ ]:
#Pegando os votos no Primeiro Turno
#OBS: existem eleições complementares e as eleições de 2º, então filtrei pelo código das eleições ordinarias do 1ª turno
detalhe_votacao_zona = dados_detalhe_votacao[(dados_detalhe_votacao.CD_ELEICAO == 426)]
detalhe_votacao_zona

NR_TURNO  CD_ELEICAO          NM_MUNICIPIO  NR_ZONA  DS_CARGO  \
0           1         426            PARIPUEIRA       17  Prefeito   
1           1         426            PARIPUEIRA       17  Vereador   
2           1         426           ÁGUA BRANCA       39  Prefeito   
3           1         426           ÁGUA BRANCA       39  Vereador   
4           1         426             PARICONHA       39  Prefeito   
..        ...         ...                   ...      ...       ...   
209         1         426               CRAÍBAS       31  Vereador   
210         1         426  SENADOR RUI PALMEIRA       51  Prefeito   
211         1         426  SENADOR RUI PALMEIRA       51  Vereador   
212         1         426       TEOTÔNIO VILELA       34  Prefeito   
213         1         426       TEOTÔNIO VILELA       34  Vereador   

     QT_APTOS_TOT  QT_COMPARECIMENTO  QT_ABSTENCOES ST_VOTO_EM_TRANSITO  \
0           10382               8677           1705                   N   
1           10382               8677           1705                   N   
2           15296              11597           3699                   N   
3           15296              11597           3699                   N   
4            8736               7046           1690                   N   
..            ...                ...            ...                 ...   
209         18372              15703           2669                   N   
210          8854               6805           2049                   N   
211          8854               6805           2049                   N   
212         29308              21519           7789                   N   
213         29308              21519           7789                   N   

     QT_VOTOS_NOMINAIS  QT_VOTOS_BRANCOS  QT_VOTOS_NULOS  QT_VOTOS_LEGENDA  \
0                 8162               150             365                 0   
1                 7862               117             260               438   
2                11012                96             489                 0   
3                10379               103             575               540   
4                 6690                56             300                 0   
..                 ...               ...             ...               ...   
209              14184               174             503               841   
210               6396                75             334                 0   
211               5995                43             415               352   
212              19453               687            1379                 0   
213              18946               422             857              1294   

     QT_VOTOS_ANULADOS  QT_VOTOS_NULO_TECNICO  QT_VOTOS_ANULADO_SUB_JUDICE  \
0                    0                      0                            0   
1                    0                      0                            0   
2                    0                      0                            0   
3                    0                      0                            0   
4                    0                      0                            0   
..                 ...                    ...                          ...   
209                  0                      1                            0   
210                  0                      0                            0   
211                  0                      0                            0   
212                  0                      0                            0   
213                  0                      0                            0   

     QT_VOTOS_SEM_CAND_P_VOTAR  
0                            0  
1                            0  
2                            0  
3                            0  
4                            0  
..                         ...  
209                          0  
210                          0  
211                          0  
212                          0  
213                       

In [ ]:
# Juntando o número de votos de zonas eleitorais diferentes no mesmo municipio e cargo
# Soma os cada tipo de voto quando 'NM_MUNICIPIO', 'DS_CARGO' são identicos
# Exclui as colunas do turno, código da eleição e zona eleitoral
new = detalhe_votacao_zona.groupby(['NM_MUNICIPIO', 'DS_CARGO']).sum().reset_index()
detalhe_votacao = new.drop(columns=['NR_TURNO', 'CD_ELEICAO', 'NR_ZONA'])
detalhe_votacao

<ipython-input-20-3196222593f3>:4: FutureWarning: The default value of numeric_only in DataFrameGroupBy.sum is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  new = detalhe_votacao_zona.groupby(['NM_MUNICIPIO', 'DS_CARGO']).sum().reset_index()


NM_MUNICIPIO  DS_CARGO  QT_APTOS_TOT  QT_COMPARECIMENTO  \
0                ANADIA  Prefeito         12411               9514   
1                ANADIA  Vereador         12411               9514   
2             ARAPIRACA  Prefeito        143187             115778   
3             ARAPIRACA  Vereador        143187             115778   
4               ATALAIA  Prefeito         30331              23630   
..                  ...       ...           ...                ...   
199  UNIÃO DOS PALMARES  Vereador         44953              34512   
200              VIÇOSA  Prefeito         19668              15622   
201              VIÇOSA  Vereador         19668              15622   
202         ÁGUA BRANCA  Prefeito         15296              11597   
203         ÁGUA BRANCA  Vereador         15296              11597   

     QT_ABSTENCOES  QT_VOTOS_NOMINAIS  QT_VOTOS_BRANCOS  QT_VOTOS_NULOS  \
0             2897               9064               105             345   
1             2897               8602               100             454   
2            27409             108598              2467            4613   
3            27409             102225              3149            3765   
4             6701              22443               243             944   
..             ...                ...               ...             ...   
199          10441              29401               490             986   
200           4046              14870               190             562   
201           4046              13870               268             542   
202           3699              11012                96             489   
203           3699              10379               103             575   

     QT_VOTOS_LEGENDA  QT_VOTOS_ANULADOS  QT_VOTOS_NULO_TECNICO  \
0                   0                  0                      0   
1                 358                  0                      0   
2                   0                  0                    100   
3                5818                  0                    821   
4                   0                  0                      0   
..                ...                ...                    ...   
199              2008                  0                     34   
200                 0                  0                      0   
201               942                  0                      0   
202                 0                  0                      0   
203               540                  0                      0   

     QT_VOTOS_ANULADO_SUB_JUDICE  QT_VOTOS_SEM_CAND_P_VOTAR  
0                              0                          0  
1                              0                          0  
2                              0                          0  
3                              0                          0  
4                              0                          0  
..                           ...                        ...  
199                         1593                          0  
200                            0                          0  
201                            0                          0  
202                            0                          0  
203                            0                          0  

[204 rows x 13 columns]

#### Manipulando os dados

##### Verficar o número total de municipios presentes

In [ ]:
#Calculando o número de municipios e o numero de candidatos por municipio
dados_detalhe_votacao[['NM_MUNICIPIO']].value_counts()

NM_MUNICIPIO     
MACEIÓ               15
ARAPIRACA             4
CAMPO GRANDE          3
PIRANHAS              2
PINDOBA               2
                     ..
IBATEGUARA            2
GIRAU DO PONCIANO     2
FLEXEIRAS             2
FELIZ DESERTO         2
ÁGUA BRANCA           2
Length: 102, dtype: int64

Conclusão: 
* Há 102 municipios quantificados, ou seja, todos os municipios do estado.
* 



##### Verificar valores Ausentes

In [ ]:
#Valores não-nulos por coluna
dados_detalhe_votacao.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 220 entries, 0 to 219
Data columns (total 17 columns):
 #   Column                       Non-Null Count  Dtype 
---  ------                       --------------  ----- 
 0   NR_TURNO                     220 non-null    int64 
 1   CD_ELEICAO                   220 non-null    int64 
 2   NM_MUNICIPIO                 220 non-null    object
 3   NR_ZONA                      220 non-null    int64 
 4   DS_CARGO                     220 non-null    object
 5   QT_APTOS_TOT                 220 non-null    int64 
 6   QT_COMPARECIMENTO            220 non-null    int64 
 7   QT_ABSTENCOES                220 non-null    int64 
 8   ST_VOTO_EM_TRANSITO          220 non-null    object
 9   QT_VOTOS_NOMINAIS            220 non-null    int64 
 10  QT_VOTOS_BRANCOS             220 non-null    int64 
 11  QT_VOTOS_NULOS               220 non-null    int64 
 12  QT_VOTOS_LEGENDA             220 non-null    int64 
 13  QT_VOTOS_ANULADOS            220 no

In [ ]:
#Número de valores ausentes para cada coluna
dados_detalhe_votacao.isnull().sum()

NR_TURNO                       0
CD_ELEICAO                     0
NM_MUNICIPIO                   0
NR_ZONA                        0
DS_CARGO                       0
QT_APTOS_TOT                   0
QT_COMPARECIMENTO              0
QT_ABSTENCOES                  0
ST_VOTO_EM_TRANSITO            0
QT_VOTOS_NOMINAIS              0
QT_VOTOS_BRANCOS               0
QT_VOTOS_NULOS                 0
QT_VOTOS_LEGENDA               0
QT_VOTOS_ANULADOS              0
QT_VOTOS_NULO_TECNICO          0
QT_VOTOS_ANULADO_SUB_JUDICE    0
QT_VOTOS_SEM_CAND_P_VOTAR      0
dtype: int64

**Conclusão**: não há valores faltantes nessa tabela

# Identificando o perfil do Eleitor

## Tabela 4 - Dados do Eleitor

**Pricipais atributos do dataset**: 

*   NR_TURNO - Búmero do turno
*   SG_UF	- Unidade da Federação
*   NM_MUNICIPIO - Nome do município
*   NR_ZONA - Número da Zona Eleitoral
*   CD_GENERO - Código do gênero do eleitor
*   DS_GENERO - Gênero do eleitor
*   CD_ESTADO_CIVIL - Código do estado civil do eleitor 
*   DS_ESTADO_CIVIL - Estado civil do eleitor de acordo com a última atualização realizada pelo mesmo na Justiça Eleitora
*   CD_FAIXA_ETARIA - Código da faixa etária
* DS_FAIXA_ETARIA - Faixa etária
* CD_GRAU_ESCOLARIDADE - Código do grau de escolaridade do eleitor de acordo com a última atualização realizada pelo mesmo na Justiça Eleitoral.
* DS_GRAU_ESCOLARIDADE - Grau de escolaridade do eleitor
* QT_APTOS - Quantidade de eleitores aptos a votar naquele município e 
zona no ano eleitoral
* QT_COMPARECIMENTO - Quantidade de eleitores aptos que compareceram às 
eleições naquele município e zona no ano eleitoral.
* QT_ABSTENCAO - Quantidade de eleitores aptos que não compareceram às 
eleições naquele município e zona no ano eleitoral
* QT_COMPARECIMENTO_DEFICIENCIA - Quantitativo de eleitores aptos com deficiência oumobilidade reduzida que compareceram às eleições 
naquele município e zona no ano eleitoral
* QT_ABSTENCAO_DEFICIENCIA - Quantitativo de eleitores aptos com deficiência ou 
mobilidade reduzida que não compareceram às eleições naquele município e zona no ano eleitoral.
* QT_COMPARECIMENTO_TTE - Quantitativo de eleitores aptos que solicitaram 
transferência temporária de eleitor (TTE) e que compareceram às eleições naquele município e zona no ano eleitoral.
* QT_ABSTENCAO_TTE - Quantitativo de eleitores aptos que solicitaram transferência temporária de eleitor (TTE) e que não compareceram às eleições naquele município e zona no ano eleitoral


**Quantidade de linhas** = 4770970

**Quantidade de Municipios** =  

**Problemas encontrados**:  

In [ ]:
#Tabela com dados sobre os cadidados
dados_eleitor = pd.read_csv('/content/drive/My Drive/Visualização Computacional/perfil_comparecimento_abstencao_2020.csv', sep=";", encoding='latin-1')
dados_eleitor

DT_GERACAO HH_GERACAO  ANO_ELEICAO  NR_TURNO SG_UF  CD_MUNICIPIO  \
0        21/12/2020   14:48:46         2020         2    SP         71072   
1        21/12/2020   14:48:46         2020         2    SP         71072   
2        21/12/2020   14:48:46         2020         2    SP         71072   
3        21/12/2020   14:48:46         2020         2    SP         71072   
4        21/12/2020   14:48:46         2020         2    SP         71072   
...             ...        ...          ...       ...   ...           ...   
4770965  21/12/2020   14:48:46         2020         1    CE         14273   
4770966  21/12/2020   14:48:46         2020         1    CE         14273   
4770967  21/12/2020   14:48:46         2020         1    CE         14273   
4770968  21/12/2020   14:48:46         2020         1    CE         14273   
4770969  21/12/2020   14:48:46         2020         1    CE         14290   

        NM_MUNICIPIO  NR_ZONA  CD_GENERO  DS_GENERO  ...  DS_FAIXA_ETARIA  \
0          SÃO PAULO      328          2  MASCULINO  ...     75 a 79 anos   
1          SÃO PAULO      328          2  MASCULINO  ...     85 a 89 anos   
2          SÃO PAULO      328          2  MASCULINO  ...     95 a 99 anos   
3          SÃO PAULO      328          2  MASCULINO  ...     30 a 34 anos   
4          SÃO PAULO      328          2  MASCULINO  ...     40 a 44 anos   
...              ...      ...        ...        ...  ...              ...   
4770965      ITAPAJÉ       41          4   FEMININO  ...     30 a 34 anos   
4770966      ITAPAJÉ       41          4   FEMININO  ...     50 a 54 anos   
4770967      ITAPAJÉ       41          4   FEMININO  ...     60 a 64 anos   
4770968      ITAPAJÉ       41          4   FEMININO  ...     70 a 74 anos   
4770969    ITAPIPOCA       17          2  MASCULINO  ...          17 anos   

        CD_GRAU_ESCOLARIDADE           DS_GRAU_ESCOLARIDADE QT_APTOS  \
0                          3  ENSINO FUNDAMENTAL INCOMPLETO      269   
1                          3  ENSINO FUNDAMENTAL INCOMPLETO       78   
2                          6          ENSINO MÉDIO COMPLETO        2   
3                          1                     ANALFABETO        1   
4                          5        ENSINO MÉDIO INCOMPLETO        2   
...                      ...                            ...      ...   
4770965                    5        ENSINO MÉDIO INCOMPLETO        2   
4770966                    1                     ANALFABETO        1   
4770967                    3  ENSINO FUNDAMENTAL INCOMPLETO        5   
4770968                    2                   LÊ E ESCREVE        5   
4770969                    6          ENSINO MÉDIO COMPLETO      184   

         QT_COMPARECIMENTO QT_ABSTENCAO  QT_COMPARECIMENTO_DEFICIENCIA  \
0                       65          204                              3   
1                        3           75                              0   
2                        0            2                              0   
3                        1            0                              0   
4                        2            0                              0   
...                    ...          ...                            ...   
4770965                  2            0                              0   
4770966                  1            0                              0   
4770967                  4            1                              0   
4770968                  2            3                              0   
4770969                165           19                              1   

         QT_ABSTENCAO_DEFICIENCIA  QT_COMPARECIMENTO_TTE  QT_ABSTENCAO_TTE  
0                               6                      3                16  
1                               0                      1                 5  
2                               0                      0                 0  
3                               0                      0                 0  
4                   